/* =====================================================================
   MINNESOTA K-12 ACADEMIC STANDARDS IN MATHEMATICS, 2022 VERSION
   Source: "2022 Minnesota K-12 Academic Standards in Mathematics" (Minnesota Department of
   Education; adopted into rule in 2025, fully implemented in 2027-28), the Grade 6, Grade 7,
   Grade 8 and Grades 9-11 benchmark tables: 185 benchmarks (Grade 4 and Grade 5 tables, 80 more, added 2026-10-04 from the owner's PDF; hand-checked where fractions were lost in text extraction), 7 anchor standards, 3 strands.
   Benchmark wording is transcribed from the document. The trailing Standards-for-Mathematical-
   Practice notes and margin symbols are omitted. Inline math and superscripts that the text
   layer drops (for example k^2, 22/7, a(b)^x) were restored from the rendered pages.

   Benchmark code <band>.<strand>.<anchor>.<n>
     band    6, 7, 8, or 9 (the single high-school band, Grades 9-11)
     strand  1 Data and Probability, 2 Spatial Reasoning, 3 Patterns and Relationships
     anchor  1 Data Sciences, 2 Chance and Uncertainty (strand 1); 3 Measurement, 4 Geometry
             (strand 2); 5 Number Relationships, 6 Equivalence and Relational Thinking,
             7 Patterns and Relationships (strand 3)
   Grade 8 has no Chance and Uncertainty benchmarks in the document.
   Do not hand-edit the benchmark text; lesson tagging lives in curriculum.js.
   ===================================================================== */
const STRANDS = [
  { id: 'dp', n: 1, name: 'Data and Probability' },
  { id: 'sr', n: 2, name: 'Spatial Reasoning' },
  { id: 'pr', n: 3, name: 'Patterns and Relationships' }
];
const ANCHORS = {
  1: { strand: 1, name: "Data Sciences", text: "Identify, formulate and investigate statistical questions by collecting data, considering cultural perspectives, analyzing and interpreting data and communicating the results." },
  2: { strand: 1, name: "Chance and Uncertainty", text: "Apply and explain the concepts of probability to interpret data, generate questions, predict and make informed decisions to solve problems and communicate ideas." },
  3: { strand: 2, name: "Measurement", text: "Investigate measurement using a variety of tools, units, systems, processes and techniques in various cultures. Explain and reason with attributes, estimations and formulas to communicate measurement(s) and relationships effectively. Justify decisions and consider the reasonableness of the measurement." },
  4: { strand: 2, name: "Geometry", text: "Analyze characteristics of geometric shapes to make mathematical arguments and justifications about geometric relationships. Use visualization and geometric modeling to compare, solve problems and communicate ideas." },
  5: { strand: 3, name: "Number Relationships", text: "Describe, Interpret and use quantities, relationships between quantities, representations of quantities, and number systems. Describe operations and the relationship between operations. Use strategies and procedures accurately, efficiently and flexibly. Assess the reasonableness of the results." },
  6: { strand: 3, name: "Equivalence and Relational Thinking", text: "Use concepts and properties of equivalence and relational thinking to represent and compare numerical expressions, proportional relationships, algebraic expressions and equations." },
  7: { strand: 3, name: "Patterns and Relationships", text: "Represent and connect mathematical patterns and relationships using verbal descriptions, generalizations, tables and graphs. Use representations to generate questions, make predictions and solve mathematical problems." }
};
const STANDARDS = {
  '4.1.1.1': "Notice and describe patterns in data-rich situations or two given related data sets that are descriptive and comparative. Ask meaningful statistical questions that can be answered with data.",
  '4.1.1.2': "Collect and organize data to answer a statistical question, analyze variability and address missing, incomplete and bias in data. Represent data in a variety of ways, including technology.",
  '4.1.1.3': "Make predictions and recognize that how the data was collected impacts the reliability of predictions.",
  '4.1.1.4': "Critically analyze data visualizations, including tables, double bar graphs, timelines, line plots or spreadsheets to support a claim and solve contextual situations.",
  '4.1.2.1': "Classify probability events involving dice, coins, spinners with equal and unequal partitions and blocks in a bag as impossible, certain, likely, unlikely and equally likely.",
  '4.1.2.2': "Use a number line to connect the values of 0 to impossible, to equally likely, and 1 to certain. Approximate locations on the number line where likely and unlikely would occur based on the situation.",
  '4.2.3.1': "Classify angles as acute, right and obtuse by estimation, comparison with a right angle and by measurement.",
  '4.2.3.2': "Determine lengths to the nearest sixteenth of an inch when measuring with inches and to the nearest tenth of a centimeter when measuring in centimeters.",
  '4.2.3.3': "Measure angles with a protractor.",
  '4.2.3.4': "Determine the perimeter and area of two-dimensional figures and label with appropriate units.",
  '4.2.3.5': "Find the areas of geometric figures that can be decomposed into rectangular shapes using tools like dot or grid paper. Label area measurements using square units.",
  '4.2.3.6': "Explain why the area of a rectangle can be calculated by multiplying the length by the width and use the formula A = l × w to calculate the area of rectangles with whole number side lengths.",
  '4.2.3.7': "Make change up to 20 with place values, using and ¢ symbols appropriately.",
  '4.2.4.1': "Draw points, line segments, rays, lines, angles and perpendicular and parallel lines. Identify these in two-dimensional figures.",
  '4.2.4.2': "Create representations of triangles given the relationships among the sides (scalene, isosceles, equilateral) and the angles (acute, right, obtuse).",
  '4.2.4.3': "Sort and classify quadrilaterals in a hierarchy, including squares, rectangles, trapezoids, rhombuses, parallelograms and kites. Understand that attributes belonging to a category of two-dimensional figures also belong to all subcategories of that category.",
  '4.2.4.4': "Create a representation and describe the front, top and side views of three-dimensional figures composed of cubes and rectangular prisms.",
  '4.2.4.5': "Draw the nets of cubes. Recognize nets that will and will not form cubes.",
  '4.3.5.1': "Recognize that in a multi-digit whole number, a digit in one place represents 10 times what it represents in the place to its right.",
  '4.3.5.2': "Compare and order whole numbers from 0 to 1,000,000 with place value understanding, number lines and other tools using >, = and < symbols to record the results of comparisons.",
  '4.3.5.3': "Estimate sums and differences, within 1,000,000, using strategies based on place value, approximation and properties of operations.",
  '4.3.5.4': "Estimate products and quotients of multi-digit whole numbers by using simple multiplicative relationships, approximation and place value to assess the reasonableness of results.",
  '4.3.5.5': "Fluently multiply two numbers from 0 to 12 using flexible strategies based on the associative, commutative and distributive properties of multiplication.",
  '4.3.5.6': "Use place value language to describe how to multiply a number by 10, 100 and 1,000.",
  '4.3.5.7': "Flexibly decompose numbers into addends or factors to multiply two two-digit numbers and multiply a one-digit number, by up to a four-digit number. Justify the strategy using equations, rectangular arrays and area models.",
  '4.3.5.8': "Solve contextual situations using division with dividends up to the thousands place and using one-digit divisors. Strategies may include using visual models, partial quotients, the commutative, associative and distributive properties and repeated subtraction.",
  '4.3.5.9': "Solve multi-step contextual situations requiring the use of addition, subtraction and multiplication of multi-digit whole numbers. Use various strategies, including the relationship between operations, the use of technology and the context of the situation to assess the reasonableness of results.",
  '4.3.5.10': "Read, write, represent and plot on a number line fractional values between 0 and 3, including mixed numbers and fractions greater than 1 with denominators of 2, 3, 4, 5, 6, 8, 10 and 12. Express whole numbers as fractions and recognize fractions that are equivalent to whole numbers.",
  '4.3.5.11': "Explain why a fraction a/b is equivalent to the product a × 1/b using visual models and language.",
  '4.3.5.12': "Explain why a fraction a/b is equivalent to a fraction (n × a)/(n × b) by using visual models, with attention to how the number and size of the parts differ even though the two fractions themselves are the same size. Use this principle to recognize and generate equivalent fractions.",
  '4.3.5.13': "Compare and order fractions between 0 and 3 and justify reasoning using pictures, position on a number line and selecting, when appropriate, among strategies such as using a common numerator, referencing a benchmark and using a common denominator.",
  '4.3.5.14': "Recognize the relationship between decimals and fractions. Read and write decimals and fractions in both decimal and fraction notations using words, symbols and expanded form. Recall the fraction and decimal equivalent forms of one-half, one-quarter and three-quarters.",
  '4.3.5.15': "Compare and order decimal values to the hundredths and justify using place value language, a number line and models such as dimes, pennies, 10 × 10 grids and base 10 blocks. Use place value concepts to name and model equivalent forms of decimal values.",
  '4.3.5.16': "Use visual models to add and subtract fractions with denominators of 2, 4 and 8 with results up to 2.",
  '4.3.5.17': "Use the four operations to make financial decisions based on income, spending, saving, credit and charitable giving.",
  '4.3.6.1': "Use relational thinking to find a missing value in an open number sentence with multi-digit whole number multiplication and division expressions. Determine if the equation is true or false and justify your reasoning.",
  '4.3.6.2': "Make conjectures and justifications using the distributive property to justify multi-digit multiplication with true/false and open number equations.",
  '4.3.7.1': "Develop an explicit rule that generalizes a visual pattern relating the figure number with the number of items in that figure. Use the rule to find the number of items in figure n.",
  '4.3.7.2': "Use words to write a rule for multiplicative patterns and solve contextual situations. Compare and contrast patterns or rules that are additive and multiplicative, using a variety of strategies including tables, drawings and algebraic equations with a symbol for the unknown number to represent the situation.",
  '4.3.7.3': "Generate a number or shape pattern that follows a given descriptive rule. Identify and explain apparent features of the pattern that were not explicit in the rule itself.",
  '5.1.1.1': "Notice and describe patterns in data-rich situations or given related data sets that are descriptive and comparative. Ask meaningful statistical questions that can be answered with data.",
  '5.1.1.2': "Compare and contrast between qualitative and quantitative data.",
  '5.1.1.3': "Collect and organize data to answer statistical questions and analyze measures of center (mean and median) and variability (range). Represent data in a variety of ways, including technology.",
  '5.1.1.4': "Critically analyze data visualizations using measures of center and variability, including but not limited to double-bar graphs, line graphs and line plots to support a claim and solve situations.",
  '5.1.1.5': "Compare and contrast different data displays to determine how the visualizations impact analysis and interpretation.",
  '5.1.2.1': "List outcomes from a probability experiment in a frequency table.",
  '5.1.2.2': "Use a frequency table to record results from an experiment to make predictions. Place predictions on a number line from 0 to 1.",
  '5.2.3.1': "Develop, justify and use formulas to determine the area of parallelograms and triangles. Find the areas of polygons that can be decomposed into parallelograms and triangles.",
  '5.2.3.2': "Estimate the area of two-dimensional shapes, both polygons and non-polygons, using tools such as dot or grid paper.",
  '5.2.3.3': "Use unit cubes to measure volume. Describe a unit cube as a cube with side length 1 unit that is said to have “one cubic unit” of volume and can be used to measure volume.",
  '5.2.3.4': "Use various strategies to measure the volume and surface area of three-dimensional shapes made of a collection of unit cubes.",
  '5.2.3.5': "Find the volume of a right rectangular prism with whole-number side lengths by packing it with unit cubes. Show that the volume is the same by unit cubes as by multiplying the edge lengths (l × w × h) or by multiplying the height by the area of the base.",
  '5.2.4.1': "Classify and describe prisms and pyramids by their defining attributes and the number of edges, faces, vertices and bases.",
  '5.2.4.2': "Recognize, draw and compare different nets for prisms, pyramids, cylinders and cones.",
  '5.3.5.1': "Multiply two multi-digit numbers using an efficient strategy. Strategies include decomposing factors into factors, decomposing factors into sums or using an area model. Justify the chosen strategy using properties of operations and place value.",
  '5.3.5.2': "Divide multi-digit numbers by a one-digit or two-digit divisor using efficient and generalizable procedures based on knowledge of place value and the properties of operations that may include partial quotients and standard algorithms. Recognize that quotients can be represented in a variety of ways, including a whole number with a remainder, a fraction, a mixed number or a decimal.",
  '5.3.5.3': "Consider the context of a problem involving division to select the most useful form of the quotient and the remainder.",
  '5.3.5.4': "Solve multi-step contextual situations requiring addition, subtraction, multiplication and division of multi-digit whole numbers. Use various strategies including the inverse relationships between operations, the use of technology and the context of the situation to assess the reasonableness of results.",
  '5.3.5.5': "Generate equivalent fractions of the forms a/b = (n × a)/(n × b) and a/b = (a ÷ n)/(b ÷ n) and justify relationships using visual models.",
  '5.3.5.6': "Given a value, mentally find 0.1 more or 0.1 less, 0.01 more or 0.01 less and 0.001 more or 0.001 less than the number. Justify reasoning by referencing a visual model.",
  '5.3.5.7': "Recognize that in a multi-digit number, a digit in one place represents 10 times as much as it represents in the place to its right and 1/10 of what it represents in the place to its left.",
  '5.3.5.8': "Recognize and flexibly generate equivalences between fractions and decimals to the thousandths place and justify using visual models, place value language and symbols.",
  '5.3.5.9': "Compare and order decimal values to the thousandths. Justify using place value language and visual models.",
  '5.3.5.10': "Estimate sums and differences of fractions and mixed numbers to the nearest half. Justify reasoning using benchmarks.",
  '5.3.5.11': "Fluently add and subtract fractions with unlike denominators (including mixed numbers) and justify using equivalent fractions, visual models and the number line.",
  '5.3.5.12': "Estimate sums and differences of decimals.",
  '5.3.5.13': "Solve contextual situations using addition and subtraction of positive rational numbers represented as fractions (including mixed numbers) or decimals using visual models, equations and properties of operations.",
  '5.3.5.14': "Represent multiplication of a whole number of fractional groups, n × a/b, using visual models, including a number line, and explain how the picture shows the product.",
  '5.3.5.15': "Represent contextual multiplication situations of a fractional amount of a whole number amount, a/b of a group of n, using visual models, including a number line, and explain how the picture shows the product.",
  '5.3.5.16': "Represent contextual measurement situations using division of the form n ÷ (a/b) where n is the total and a/b is the amount per group. Use a visual model and explain how the picture shows the number of groups.",
  '5.3.5.17': "Solve multi-step contextual situations using addition and subtraction of positive rational numbers. Use various strategies, including the inverse relationships between operations and the context of the situation, to assess the reasonableness of results.",
  '5.3.5.18': "Use the four operations to compare and contrast different ways of paying and receiving payments. Identify the advantages and disadvantages of each method of payment, including checks, credit cards, debit cards and electronic payments.",
  '5.3.5.19': "Use the four operations to create an individual or group budget based on wants and needs and explore examples of debt and manageability of debt and its long-term impact.",
  '5.3.6.1': "Use relational thinking to find a missing value in an open number sentence with addition and subtraction of fractions and decimal expressions. Determine if the equation is true or false and justify the reasoning.",
  '5.3.6.2': "Make conjectures and justifications about numerical expressions involving parentheses and the four operations using the properties of operations, properties of algebra, decomposition and composition to generate equivalent numerical expressions.",
  '5.3.7.1': "Use a rule or table to represent ordered pairs of positive integers and graph these ordered pairs on a coordinate system.",
  '5.3.7.2': "Identify and explain apparent relationships between two patterns from given rules, using tables or ordered pairs on a coordinate system.",
  '5.3.7.3': "Represent contextual situations by graphing whole and half number points in the first quadrant of the coordinate plane. Interpret coordinate values of points in the context of the situation.",
  '5.3.7.4': "Use ratio tables with whole numbers to solve situations with additive and multiplicative reasoning. Interpret multiplication as scaling.",
  '5.3.7.5': "Develop an explicit rule that generalizes a visual pattern relating the figure number with the number of items in that figure. Use the rule to find the number of items in figure n.",
  '6.1.1.1': "Recognize a statistical question as one that anticipates variability in the data, compares differences between groups and collects categorical or numerical data related to the question, and accounts for it in the answer.",
  '6.1.1.2': "Design and conduct investigations and experiments to gather data, while considering cultural perspectives, to answer statistically investigative questions considering variability and justifying choice of variables.",
  '6.1.1.3': "Identify, determine and interpret measures of center (mean and median) and measures of variability (range, interquartile range, mean-absolute deviation) to answer a statistically investigative question, summarizing the distribution of data using the measures of center and variability.",
  '6.1.1.4': "Create a visualization about a data set to describe patterns, highlight relationships or illustrate features of the distribution of the data to answer or help answer their statistically investigative question. Visualizations should represent the data in appropriate ways, including tables, dot plots, stem-and-leaf plots, histograms and box plots while incorporating any other relevant information that helps to tell a story about the data.",
  '6.1.1.5': "Compare and communicate competing explanations for data trends observed, considering cultural perspectives and reasonable alternatives given the variability in findings.",
  '6.1.2.1': "Determine the sample space (set of possible outcomes) for a given experiment. Sample space may be determined by the use of tree diagrams, tables or pictorial representations.",
  '6.1.2.2': "Determine the theoretical probability of an event using the ratio between the size of the event and the size of the sample space. Represent probabilities as percentages, fractions and decimals between 0 and 1 inclusive.",
  '6.1.2.3': "Calculate experimental probabilities from experiments where the theoretical probability is known, recognizing that there may be differences between theoretical and experimental probability. Represent the probabilities as percentages, fractions and decimals between 0 and 1 inclusive. Use experimental probabilities to make predictions when actual probabilities are unknown.",
  '6.2.3.1': "Calculate the measurements of the surface area of rectangular and triangular prisms using appropriate units. Justify the formulas used. Justification may involve decomposition, nets or other models.",
  '6.2.3.2': "Calculate the measurement of the volume of prisms (including triangular and nonrectangular prisms) using appropriate units. Justify the formulas used. Justification may involve decomposition or other models.",
  '6.2.3.3': "Solve situations in various contexts involving conversion of time, weights, capacities, lengths and area within measurement systems using appropriate units.",
  '6.2.3.4': "Estimate time, weights, capacities, lengths and dollar amounts using benchmarks in measurement systems with appropriate units.",
  '6.2.3.5': "Find the area of special quadrilaterals and polygons by composing into rectangles or decomposing into triangles and other shapes. Apply these techniques in contextual mathematical situations.",
  '6.2.4.1': "Determine missing angle measures in a triangle using the fact that the sum of the interior angles of a triangle is 180°. Use models to illustrate this fact.",
  '6.2.4.2': "Decompose polygons into triangles to investigate the sum of the interior angles of polygons.",
  '6.2.4.3': "Draw polygons in the coordinate plane given coordinates for the vertices. Use coordinates to find the length of a side joining points with the same first coordinate or the same second coordinate. Apply these techniques in contextual situations.",
  '6.3.5.1': "Use positive and negative numbers to describe quantities having opposite directions or values, represent quantities in contexts and explain the meaning of 0 in situations including credits/debits, temperature above/below zero, elevation above/below sea level and positive/negative electric charge.",
  '6.3.5.2': "Locate positive and negative rational numbers on a number line. Plot ordered pairs of positive and negative rational numbers on a coordinate grid.",
  '6.3.5.3': "Interpret statements of inequality (<, >, =) as statements about the relative position of two numbers on a number line, including positive and negative rational numbers in various forms.",
  '6.3.5.4': "Factor whole numbers. Express a whole number as a product of prime factors with exponents. Identify a prime number as a whole number greater than one whose only factors are one and itself.",
  '6.3.5.5': "Find the greatest common factor of two whole numbers less than or equal to 100 and the least common multiple of two whole numbers less than or equal to 12. Use the distributive property to express a sum or difference of two whole numbers, from 1 through 100, with a common factor as a multiple of a sum or difference of two whole numbers with no common factor.",
  '6.3.5.6': "Understand the absolute value of a rational number as its distance from 0 on the number line. Interpret absolute value as magnitude for a positive or negative quantity in context.",
  '6.3.5.7': "Estimate solutions to situations with whole numbers, fractions and decimals and use the estimates to assess the reasonableness of the results in the context of the situation.",
  '6.3.5.8': "Multiply and divide fractions and mixed numbers using visual models to represent the situation leading towards generalizable algorithms.",
  '6.3.5.9': "Solve mathematical situations requiring arithmetic, including multiplication and division, with decimals, fractions and mixed numbers, explaining the solution pathway. Interpret quotients in the context of the situation.",
  '6.3.5.10': "Solve situations using the concept of a unit rate associated with a ratio a : b with b ≠ 0 in context, including constant speed and unit pricing to make purchase decisions.",
  '6.3.5.11': "Solve percent situations using visual models including tables of equivalent ratios, tape diagrams or double number lines. Apply concepts of percentage including discounts, markups, tips and commission. Situations can include identifying the part given a whole and the percentage, and identifying the percentage given the part and the whole.",
  '6.3.6.1': "Generate equivalent numerical expressions involving positive rational numbers and justify why expressions are equivalent.",
  '6.3.6.2': "Determine equivalences among fractions, decimals and percentages involving rational numbers. Convert between equivalent representations.",
  '6.3.6.3': "Represent mathematical situations using expressions, equations and inequalities involving variables and positive rational numbers.",
  '6.3.6.4': "Solve one-step equations, including equations of the form x + p = q and px = q for cases in which p, q and x are all positive rational numbers. Use number sense, properties of arithmetic and the idea of maintaining equality on both sides of the equation. Interpret a solution in the original context and assess the reasonableness of results.",
  '6.3.6.5': "Identify and use ratios to compare quantities. Understand that comparing quantities using ratios is not the same as comparing quantities using subtraction.",
  '6.3.6.6': "Solve ratio and rate situations, including mixtures and concentrations, by modeling with tables of equivalent ratios, tape diagrams, double number lines or equations.",
  '6.3.7.1': "Use variables to represent two quantities in a situation that change in relationship to one another. Write an equation to express one quantity, thought of as the dependent variable, in terms of the other quantity, thought of as the independent variable. Analyze the relationship between the dependent and independent variables using graphs and tables and relate these to the equation.",
  '7.1.1.1': "Formulate statistical investigative questions with data collection, keeping cultural perspectives in mind, which compare differences between groups, require a sample of a population and use categorical and/or numerical data.",
  '7.1.1.2': "Describe how statistics can be used to gain information about a population by examining a sample of the population. Explain how generalizations about a population are valid only when the sample is representative of that population and that random sampling tends to produce representative samples and support valid inferences.",
  '7.1.1.3': "Make inferences using statistics about population parameters based on a random sample from that population.",
  '7.1.1.4': "Understand that a set of data collected to answer a statistical question has a distribution that can be described by its center, variability and overall shape. Use measures of center and measures of variability for numerical data from random samples to draw informal comparative inferences about two populations. Justify the choice of measures of center and variability, the shape of the data distribution and the context in which the data were gathered.",
  '7.1.1.5': "Create a visualization about a data set, organizing and presenting the data in appropriate ways, including in tables, circle graphs and histograms, and incorporating any other relevant information that helps to tell a story about the data.",
  '7.1.1.6': "Compare and communicate multiple explanations for data trends observed, considering reasonable alternatives given the variability in findings and sampling methods and cultural perspectives.",
  '7.1.2.1': "Calculate probability as a fraction of sample space or as a fraction of area. Express probabilities as fractions, decimals and percentages.",
  '7.1.2.2': "Approximate the probability of a chance event, where the theoretical probability is unknown, by collecting data and observing its long-run frequency. Represent the probabilities as percentages, fractions and decimals between 0 and 1 inclusive. Use approximate probabilities to make predictions when actual probabilities are unknown.",
  '7.1.2.3': "Recognize that, just as with simple events, the probability of a compound event is the fraction of outcomes in the sample space where the compound event occurs.",
  '7.1.2.4': "Represent sample spaces for compound events by decomposing the events using methods such as organized lists, tables and/or tree diagrams. For an event described in everyday language, identify the outcomes in the sample space that compose the event.",
  '7.1.2.5': "Design and use a simulation within a computational tool to generate frequencies for compound events.",
  '7.1.2.6': "Find probabilities of compound events using organized lists, tables, tree diagrams and/or simulation via a computational tool.",
  '7.2.3.1': "Demonstrate an understanding of the proportional relationship between the diameter and circumference of a circle and that the unit rate (constant of proportionality) is π.",
  '7.2.3.2': "Calculate the circumference and area of circles to solve situations in various contexts.",
  '7.2.3.3': "Calculate the arc length and area of sectors of circles (given the central angle) to solve situations in various contexts.",
  '7.2.3.4': "Calculate the surface area and volume of cylinders. Justify the formulas used.",
  '7.2.4.1': "Graph and describe translations and reflections of figures on a coordinate grid. Determine the coordinates of the vertices of the figure after the transformation. Describe the properties of congruency when performing translations and reflections.",
  '7.2.4.2': "Describe the properties of similarity, distinguishing between similarity and congruency, compare geometric figures for similarity and determine scale factors.",
  '7.2.4.3': "Apply scale factors, length ratios and area ratios to determine side lengths and areas of similar geometric figures.",
  '7.2.4.4': "Use proportional reasoning and ratios to solve situations involving scale drawings and conversions of measurement units.",
  '7.3.5.1': "Know that every rational number can be written as the ratio of two integers and as a terminating or repeating decimal. Recognize that π is not rational but that it can be approximated by rational numbers such as 22/7 and 3.14.",
  '7.3.5.2': "Recognize opposite signs of numbers as indicating locations on opposite sides of 0 on the number line. Recognize that the opposite of the opposite of a number is the number itself, such as – (– 3) = 3. Recognize that 0 is its own opposite.",
  '7.3.5.3': "Compare positive and negative rational numbers expressed in various forms including the symbols <, >, =, ≤ and ≥.",
  '7.3.5.4': "Recognize subtraction of rational numbers as adding the additive inverse, p – q = p + (–q). Show that the distance between two rational numbers on the number line is the absolute value of their difference and apply this principle in contexts.",
  '7.3.5.5': "Create a budget using positive and negative rational numbers for an event and calculate what percentage of the total budget each category comprises. Justify choices of the allocation of the available resources.",
  '7.3.5.6': "Solve mathematical situations involving adding, subtracting, multiplying and dividing positive and negative rational numbers that are integers, fractions and terminating decimals. Use efficient and generalizable procedures. Raise positive rational numbers to whole-number exponents.",
  '7.3.5.7': "Compute unit rates associated with ratios of fractions, including ratios of lengths, areas and other quantities measured in like or different units.",
  '7.3.6.1': "Use properties of algebra to generate equivalent numerical and algebraic expressions containing rational numbers, grouping symbols and whole number exponents. Properties of algebra include associative, commutative and distributive laws.",
  '7.3.6.2': "Represent and solve contextual situations resulting in two-step equations and inequalities involving variables and positive/negative rational numbers. Graph the solution set of the inequality and interpret the solution in context.",
  '7.3.6.3': "Evaluate algebraic expressions, including expressions containing rational numbers, absolute value and whole number exponents, by applying computational hierarchy of operations at specified values of their variables.",
  '7.3.6.4': "Solve multi-step situations involving proportional relationships in numerous contexts using models, such as tables of equivalent ratios involving scaling up and down, tape diagrams, double number lines or equations.",
  '7.3.6.5': "Solve multi-step financial literacy situations including simple interest, tax, markups and markdowns, tips and commissions, fees, percent increase and decrease and percent error. Distinguish between sales tax and income tax for earned wages. Situations include finding the whole, the part and the percent.",
  '7.3.7.1': "Represent proportional relationships with tables, verbal descriptions, symbols, equations and graphs. Translate from one representation to another. Determine the unit rate (constant of proportionality or rate of change) given any of these representations.",
  '7.3.7.2': "Express a relationship between two variables, the independent (x) and the dependent (y) as proportional if it can be written in the form y/x = k or y = kx. Distinguish proportional relationships from non-proportional relationships, including relationships where the x and y value are not 0.",
  '7.3.7.3': "Determine whether two quantities are in a proportional relationship by testing for equivalent ratios in a table or graphing on a coordinate plane and by observing whether the graph is a straight line through the origin. Use graphing technology to examine the relationship between the unit rate and the line for a given situation.",
  '8.1.1.1': "Formulate statistical investigative questions, such as questions about variation, the differences between groups and associations between two numerical variables.",
  '8.1.1.2': "Construct and interpret scatter plots for bivariate measurement data to investigate patterns of association between two quantities. Describe patterns such as clustering, outliers, positive or negative association, linear association and nonlinear association.",
  '8.1.1.3': "Identify when to use straight lines to model relationships between two quantitative variables. For scatter plots that suggest a linear association, informally fit a straight line and assess the model fit by judging the closeness of the data points to the line.",
  '8.1.1.4': "Use the equation of a linear model to solve situations in the context of bivariate measurement data. Interpret the slope and intercepts in context of the variables.",
  '8.1.1.5': "Create data visualizations about a data set. Organize and present the data in appropriate ways, including in tables and scatter plots, and incorporate other relevant information that helps to tell a story and support a claim about the data.",
  '8.1.1.6': "Compare and communicate competing explanations for data trends observed, considering the reasonableness of the model’s predictions and correlation versus causation.",
  '8.2.3.1': "Informally justify the Pythagorean Theorem and its converse by using measurements, diagrams or computer software.",
  '8.2.3.2': "Apply the Pythagorean Theorem to solve multi-step contextual situations by determining unknown side lengths in right triangles in both two-and three-dimensional shapes.",
  '8.2.3.3': "Determine the distance between two points on a horizontal or vertical line in a coordinate system. Use the Pythagorean Theorem to find the distance between any two points in a coordinate system.",
  '8.2.4.1': "Use similar triangles to explain why the slope m is the same between any two distinct points on a non-vertical line in the coordinate plane. Derive the equation y = mx for a line through the origin and the equation y = mx + b for a line intercepting the vertical axis at b.",
  '8.2.4.2': "Given a line on a coordinate plane and the coordinates of a point not on the line, find lines through that point that are parallel and perpendicular to the given line, using graphing technology or hand drawn graphs.",
  '8.2.4.3': "Identify the different types of solutions possible for a system of linear equations (no solution, one solution, infinitely many solutions). Using slope, compare the number of solutions to the graphical representation of pairs of lines that are intersecting, parallel or identical.",
  '8.3.5.1': "Classify real numbers as rational or irrational. Know that when a square root of a positive integer is not an integer, then it is irrational.",
  '8.3.5.2': "Use rational approximations of irrational numbers to compare the size of irrational numbers and locate them approximately on a number line. Estimate the value of expressions involving irrational numbers.",
  '8.3.5.3': "Know and apply the properties of positive and negative integer exponents to generate equivalent numerical expressions.",
  '8.3.5.4': "Express approximations of very large and very small numbers using scientific notation. Understand how technology displays numbers in scientific notation. Compare numbers expressed in scientific notation using the symbols <, >, =, ≤ and ≥.",
  '8.3.5.5': "Multiply and divide numbers expressed in scientific notation. Express answers in scientific notation.",
  '8.3.5.6': "Solve situations in various contexts involving calculating and comparing simple and compound interest. Compound interest situations are limited to compounded annually.",
  '8.3.5.7': "Solve multi-step contextual situations comparing how interest rate and loan length affect the cost of credit. Calculate the total cost of repaying a loan under various rates of interest and over different periods of time.",
  '8.3.5.8': "Compare and contrast employment opportunities and their payment methods, including per hour, with or without tips, salary, per diem and piecework pay. Justify financial decisions with representations, including linear relationships.",
  '8.3.6.1': "Justify steps in generating equivalent algebraic expressions and identify the properties used. Properties include the associative, commutative, distributive, identity and inverse.",
  '8.3.6.2': "Evaluate algebraic expressions, including expressions containing radicals and absolute values, by applying computational hierarchy of operations at specified values of their variables.",
  '8.3.6.3': "Solve multi-step equations in one variable, including equivalent linear expressions. Solve for one variable in a multivariable equation in terms of the other variables. Justify the steps by identifying the properties of the equality used.",
  '8.3.6.4': "Use the relationship between square roots and squares of a number to solve situations.",
  '8.3.6.5': "Represent linear relationships in point-slope and standard form and convert to slope-intercept form.",
  '8.3.6.6': "Reason abstractly, involving variables as a point, slope or intercept, to compare general forms of linear relationships, including point-point, point-slope, standard form and slope-intercept form.",
  '8.3.6.7': "Represent relationships in various contexts using multi-step linear inequalities. Solve linear inequalities using properties of inequalities. Graph the solutions on a number line and interpret the solutions in context.",
  '8.3.6.8': "Represent relationships in various contexts with equations and inequalities involving the absolute value of a linear expression. Solve such equations and inequalities and graph the solutions on a number line.",
  '8.3.6.9': "Represent relationships in various contextual situations using systems of linear equations. Solve systems of linear equations in two variables, symbolically and graphically, understanding that the solution corresponds to the point of intersection of their graphs.",
  '8.3.7.1': "Compare graphical properties of proportional and non-proportional linear relationships, including slope.",
  '8.3.7.2': "Analyze visual patterns to distinguish between linear and non-linear patterns. For linear patterns, describe how a pattern is changing, name the nth term and write an equation to generalize the nth term.",
  '8.3.7.3': "Recognize that a function is a rule that assigns each input to exactly one output. Use the function to represent the relationship in which changing the input (independent) variable, by an amount, leads to a change in the output (dependent) variable, a constant multiplied by that amount. Recognize that the graph of a function is the set of ordered pairs consisting of an input and the corresponding output. Use functional notation, such as f(x), to represent such relationships.",
  '8.3.7.4': "Represent linear functions with tables, verbal descriptions, symbols, equations and graphs. Translate from one representation to another.",
  '8.3.7.5': "Explain how changes to the values m or b in the linear function f(x) = mx + b affect the graph of the function. Use graphing technology to examine these effects. Recognize that the graph of the linear equation y = mx + b comes from b units translation of y = mx graph.",
  '8.3.7.6': "Identify graphical properties of linear functions in the form f(x) = mx + b, including slope, y-intercept and x-intercept. Know that the graph is a straight line, the slope (m) equals the rate of change, the y-intercept (b) is the value of the function at x = 0 and the x-intercept is the value of the function at f(x) = 0.",
  '8.3.7.7': "Recognize that an arithmetic sequence is a linear function that can be expressed in the form f(x) = mx + b, where x = 0, 1, 2, 3,....",
  '8.3.7.8': "Recognize that a geometric sequence is a non-linear function that can be expressed in the form f(x) = a(b)^x, where x = 0, 1, 2, 3,….",
  '8.3.7.9': "Represent arithmetic and geometric sequences using equations, tables, graphs and verbal descriptions and use them to solve situations.",
  '9.1.1.1': "Formulate statistical investigative questions and pose hypotheses. These include questions about variation or the differences between groups, associations between quantitative and categorical variables or pairing together multiple analyses.",
  '9.1.1.2': "Explain how choices concerning data collection methods can affect the quality, size, speed, accessibility and cost of the data.",
  '9.1.1.3': "Analyze issues of bias by considering data collection methods and cultural perspectives.",
  '9.1.1.4': "Explain the purposes of and differences among sample surveys, experiments and observational studies. Explain whether randomization in each allows for conclusions of causation and/or generalization of a population.",
  '9.1.1.5': "Analyze and explain when arguments based on data confuse correlation and causation.",
  '9.1.1.6': "Compute using technology or estimate the correlation coefficient of a linear model. Interpret the linear model in the context of the data.",
  '9.1.1.7': "Use the mean and standard deviation of a data set to fit it to a normal distribution and to estimate population percentages. Identify data sets for which such a procedure is not appropriate. Tools can include calculators, spreadsheets, apps or tables.",
  '9.1.1.8': "Use data from a random sample to draw inferences about a population with an unknown characteristic of interest. Generate multiple samples or simulated samples of the same size to gauge the variation in estimates or predictions.",
  '9.1.1.9': "Use statistics appropriate to the shape of the data distribution to compare the center and spread of two or more data sets.",
  '9.1.1.10': "Create and analyze data displays, including scatter plots, histograms and boxplots using technology.",
  '9.1.1.11': "Identify, create and compare statistical models with linear and exponential functions, including linear regression. Assess the reasonableness of model fit using residuals and correlation coefficients.",
  '9.1.1.12': "Examine and discuss competing explanations for data trends observed such as confounding variables. Respond to competing arguments or interpretations of the data of different community groups, paying careful attention to what conclusions the data supports.",
  '9.1.1.13': "Analyze and interpret data using various measures, such as difference in shapes, center and spread to draw conclusions, identify trends and describe relationships, accounting for possible effects of extreme data points (outliers).",
  '9.1.1.14': "Evaluate reports based on published data by identifying the source of the data, the design of the study and the way the data are analyzed and displayed.",
  '9.1.1.15': "Identify and explain misleading uses of data along with how to use spreadsheets, tables or graphing technology to recognize and analyze distortions in data displays. Use interactive data visualizations to support and influence different points of view.",
  '9.1.2.1': "Select and apply counting procedures such as the multiplication and addition principles, permutations, combinations and tree diagrams to determine the elements and size of a sample space.",
  '9.1.2.2': "Describe events as subsets of a sample space using characteristics of the outcomes. Use Venn diagrams, tables or lists to depict events and compute event sizes. Create representations to find unions, intersections and complements of events.",
  '9.1.2.3': "Apply probability concepts, such as intersections, unions and complements of events, and conditional probability and independence, to calculate probabilities and solve situations.",
  '9.1.2.4': "Calculate experimental probabilities by repeatedly performing simulations or experiments involving a probability model and by using relative frequencies of outcomes. Recognize that as the number of trials increases, the closer the experimental probability approaches the theoretical probability.",
  '9.1.2.5': "Construct and interpret two-way frequency tables when two categories are associated with each object being classified. Use the two-way table to decide if events are independent and to calculate conditional probabilities.",
  '9.1.2.6': "Compare the recursion to create the nth row of Pascal’s triangle, the recursion to expand (x + y)^n, the recursion to generate all sequences of heads and tails on n coin flips and the recursion to generate all subsets of a set with n elements. Establish connections among the various representations.",
  '9.1.2.7': "Calculate and make decisions based on expected values using theoretical or experimental probabilities in scenarios, including finance or games of chance.",
  '9.1.2.8': "Calculate and make decisions to obtain a desired outcome (maximum or minimum value or maximum or minimum probability) based on expected value and theoretical or experimental probabilities in scenarios such as games of chance or finance.",
  '9.2.3.1': "Apply the Pythagorean Theorem and distance formula to compute perimeters of polygons and areas of right triangles and rectangles on coordinate planes.",
  '9.2.3.2': "Apply properties of 45°-45°-90° and 30°-60°-90° triangles to solve situations and logically justify results.",
  '9.2.3.3': "Use trigonometric ratios and the Pythagorean Theorem and its converse to solve contextual situations, including right triangles or polygons that can be decomposed into triangles.",
  '9.2.3.4': "Develop, justify and use decomposition to determine the formula for surface area and volume of various three-dimensional figures.",
  '9.2.3.5': "Use the formulas for surface area and volume of various three-dimensional figures to solve multi-step contextual situations.",
  '9.2.3.6': "Use units of measure and dimensional analysis to solve multi-step situations. Interpret units consistently in formulas. Interpret the scale and the origin in graphs and data displays.",
  '9.2.3.7': "Compute the unit cost and total cost to cover different areas and volumes in applications, such as painting, carpeting and gardening. Optimize costs for various models, including linear and quadratic. Use technology, including spreadsheets.",
  '9.2.3.8': "Use similarity to determine the side ratios in right triangles as properties of the angles in the triangle, leading to definitions of trigonometric ratios for acute angles.",
  '9.2.3.9': "Apply dilations of scale factor k on length, area and volume and recognize the effect is multiplication by k, k², k³ respectively.",
  '9.2.4.1': "Apply properties of angles, including corresponding, exterior, interior, vertical, complementary and supplementary angles, to solve situations and logically justify results.",
  '9.2.4.2': "Apply properties of equilateral, isosceles and scalene triangles to solve situations and logically justify results.",
  '9.2.4.3': "Apply properties such as interior and exterior angles and parallel and perpendicular sides to define, classify and solve situations involving regular and irregular polygons.",
  '9.2.4.4': "Apply properties of congruent figures to solve situations and logically justify results.",
  '9.2.4.5': "Accurately interpret and use words and phrases such as “if ... then,” “if and only if,” “all” and “not.” Recognize the logical relationships between an “if ... then” statement and its inverse, converse and contrapositive.",
  '9.2.4.6': "Analyze the validity of a logical argument and give counterexamples to disprove a statement.",
  '9.2.4.7': "Construct logical arguments using axioms, definitions, theorems and postulates that clearly justify the reasoning.",
  '9.2.4.8': "Identify, describe and solve situations using relationships among inscribed angles, circumscribed angles, radii and chords in circles.",
  '9.2.4.9': "Describe and solve situations using the relationships of angles formed outside the circle for both secants and tangent lines.",
  '9.2.4.10': "Apply properties of similar figures to solve situations and logically justify results.",
  '9.2.4.11': "Show that two triangles are similar using the AA, SAS and SSS similarity criteria.",
  '9.2.4.12': "Make geometric constructions with a variety of tools, including dynamic geometric technology, to examine theorems, make and test conjectures, represent transformations and develop mathematical reasoning skills in multi-step situations.",
  '9.2.4.13': "Create and compare rigid and non-rigid transformations, and connect the preimage and image to congruence.",
  '9.2.4.14': "Describe the steps used to show various sequences of transformations, applying reflections, rotations, translations and/or dilations of geometric figures that map one figure onto the other.",
  '9.2.4.15': "Apply geometric methods to solve design situations, including designing an object or structure to satisfy physical constraints or optimize resources.",
  '9.2.4.16': "Apply concepts of density based on area and volume in modeling contextual situations, including population density, BTUs per cubic foot and data storage.",
  '9.3.5.1': "Add, subtract, multiply and divide numbers in scientific notation.",
  '9.3.5.2': "Compare the definition of rational exponents and properties of radicals. Explain how the definition of rational exponents follows from extending the properties of integer exponents, allowing for a notation for radicals in terms of rational exponents.",
  '9.3.5.3': "Apply knowledge of number systems extending from whole numbers to integers, from integers to rational numbers, from rational numbers to real numbers and from real numbers to complex numbers to solve equations.",
  '9.3.5.4': "Use matrices to represent and manipulate data and interpret the results in context. Add, subtract and multiply matrices of appropriate dimensions. Multiply matrices by scalars.",
  '9.3.5.5': "Estimate and verify the cost of an item, including multiple discounts and taxes. Show an understanding of the order of operations.",
  '9.3.5.6': "Assess the reasonableness of a solution in its given context, including financial literacy applications. Compare the solution to appropriate graphical or numerical estimates. Interpret a solution in the original context.",
  '9.3.5.7': "Use the structure of an expression, equation and/or formula to create an equivalent form that is more helpful given the situation. Rearrange formulas to highlight a quantity of interest, using the same reasoning in solving equations.",
  '9.3.5.8': "Use the structure of an expression to write it in multiple ways.",
  '9.3.5.9': "Find and evaluate the composition of multiple functions.",
  '9.3.5.10': "Compute the time it takes to pay off a loan given the interest rate, loan amount and monthly payment. Determine the change in cost by the variation in loan amount, fixed or variable interest rates and payment amounts. Use technology, including spreadsheets.",
  '9.3.5.11': "Compute the total payments to pay off a loan given the interest rate, loan amount and monthly payment. Compare the total payments for various monthly payments and various interest rates. Use technology, including spreadsheets.",
  '9.3.5.12': "Compare different types of retirement plans, considering after tax or pretax contributions, employer match contributions, the benefit of starting contributions early and the consequences of use prior to retirement.",
  '9.3.6.1': "Add, subtract and multiply polynomials.",
  '9.3.6.2': "Reason abstractly to compare general forms of quadratics, including vertex form, general form, factored form and the graph. Develop procedures to convert from one form to another.",
  '9.3.6.3': "Choose and produce an equivalent form of a quadratic function, using symbolic and graphical methods, to identify the vertex, line of symmetry and intercepts of the parabola.",
  '9.3.6.4': "Factor polynomials including common monomial factors from polynomials, quadratic polynomials and the difference of two squares.",
  '9.3.6.5': "Solve quadratic equations by appropriate methods using factoring, completing the square, graphing or the quadratic formula. Find non-real complex roots when they exist.",
  '9.3.6.6': "Compare the equation of a circle, the Pythagorean Theorem and the Distance Formula. Complete the square to find the center and radius of a circle given an equation.",
  '9.3.6.7': "Solve situations involving relationships which are inversely proportional in various contexts, including rates.",
  '9.3.6.8': "Apply the properties of rational exponents and radicals to generate equivalent algebraic expressions.",
  '9.3.7.1': "Represent and solve situations in various contexts, including financial literacy, using systems of linear equations, systems of linear inequalities and exponential and quadratic functions.",
  '9.3.7.2': "Translate between graphs of quadratic, exponential and other functions (including absolute value, rational and polynomial), tables and symbolic representations. Sketch graphs and use graphing technology to graph functions.",
  '9.3.7.3': "Determine how vertical/ horizontal reflecting, translating and scaling affect the symbolic and graphical forms of a function. Use graphing technology to examine transformations.",
  '9.3.7.4': "Express the terms in an arithmetic or geometric sequence recursively and by giving an explicit formula.",
  '9.3.7.5': "Express recursive patterns using recursive formulas. Calculate sequences defined by recursive formulas.",
  '9.3.7.6': "Find the domain and range of functions defined symbolically, graphically or in a context, including piecewise and step functions. Express solutions and recognize that some answers obtained may not be valid, including cases where the function inputs are discrete instead of continuous.",
  '9.3.7.7': "Describe the graph of a function using key features such as intercepts, maxima/minima, intervals of increase and decrease and end behavior. Draw conclusions from graphs of functions and other relations.",
  '9.3.7.8': "Define the compounding of interest n times per year according to a recursive formula. Compare the recursive definition of interest to the recursive definition of a geometric sequence t(n) = r(t(n – 1)). Compare the interest formula to the general form of an exponential function y = a(b)^x. Explain the purpose of each part of the interest formula.",
  '9.3.7.9': "Find the inverse of a given function and justify the results using tables, graphs or algebra.",
  '9.3.7.10': "Use the concept of a function as a connection between inputs and outputs to find function values and use function notation."
};
