/* =====================================================================
   PRACTICE (strings): every sentence a student sees from the practice generators, keyed, with {slots}.
   Nothing is written into the logic, so a translation is a copy of this table. TeX is in String.raw-style
   double-backslash form inside normal strings. Do not put a literal {word} in TeX: {word} is a slot.
   ===================================================================== */
Practice.T = {
  /* ---- answer formats (shown under the answer box) ---- */
  'ans.whole': 'Enter a whole number.',
  'ans.number': 'Enter a number. You can write a whole number, a decimal, or a fraction like 3/4.',
  'ans.fraction': 'Enter a fraction in simplest form, like 5/6. A mixed number like 1 1/6 or a decimal that ends is fine too.',
  'ans.length': 'Enter a number. You may add the unit if you like.',
  'ans.pair': 'Enter the pair as (x, y), for example (2, -1).',
  'word.add': 'Add',
  'word.subtract': 'Subtract',
  'form.simplify': 'That value is right, but the fraction is not in simplest form. Divide the top and bottom by the same number, then enter it again.',

  /* ---- G4: multiplying multi-digit numbers ---- */
  'mult.lv1': 'A two-digit number times a one-digit number, small.',
  'mult.lv2': 'A two-digit number times a one-digit number, up to 99 by 9.',
  'mult.lv3': 'A three-digit number times a one-digit number.',
  'mult.lv4': 'Two two-digit numbers, small.',
  'mult.lv5': 'Two two-digit numbers, up to 99 by 99.',
  'mult.lv6': 'A three-digit number times a two-digit number.',
  'mult.p.eq': 'Find \\({a} \\times {b}\\).',
  'mult.p.chairs': 'A hall has {a} rows of chairs with {b} chairs in each row. How many chairs are there in all?',
  'mult.p.boxes': 'One box holds {b} pencils. How many pencils are in {a} boxes?',
  'mult.h1': 'Draw an area model. Break each number into hundreds, tens and ones, and multiply the pieces.',
  'mult.h2': 'Start with the first piece. {first}',
  'mult.h3': 'Here are all the pieces of the area model: {list}. Now add them.',
  'mult.s1': 'Break each number into place-value pieces: \\({a} = {pa}\\) and \\({b} = {pb}\\).',
  'mult.s1b': 'Break {a} into place-value pieces: \\({a} = {pa}\\). The other number, {b}, stays whole.',
  'mult.s2': 'Multiply each piece by each piece: {list}.',
  'mult.s3': 'Add the pieces: \\({sum}\\).',
  'g4-multiply.mc.missing-middle-pieces': 'It looks like you multiplied tens by tens and ones by ones only. An area model has four pieces. Do not forget tens times ones, and ones times tens.',
  'g4-multiply.mc.digits-without-place-value': 'It looks like you multiplied the digits as if each one meant just itself. A 4 in the tens place means 40. Multiply the whole pieces, like 40 times 5.',
  'g4-multiply.mc.left-out-the-ones-piece': 'It looks like one piece is missing. The ones digit also has to be multiplied, then added to the rest.',

  /* ---- G5: adding and subtracting fractions ---- */
  'frac.lv1': 'Add two fractions when one denominator is a multiple of the other. The sum is less than 1.',
  'frac.lv2': 'Add two fractions with different denominators that share no factor. The sum is less than 1.',
  'frac.lv3': 'Add two fractions with unlike denominators. The sum can be more than 1.',
  'frac.lv4': 'Subtract fractions with unlike denominators.',
  'frac.lv5': 'Add or subtract with larger denominators that share a factor, like 6 and 4.',
  'frac.p.add': 'Add. \\({T1} + {T2}\\)',
  'frac.p.sub': 'Subtract. \\({T1} - {T2}\\)',
  'frac.p.pizza': 'Mia ate \\({T1}\\) of a pizza at lunch and \\({T2}\\) of the same pizza at dinner. How much of the pizza did she eat in all?',
  'frac.p.cups': 'A recipe uses \\({T1}\\) cup of milk and \\({T2}\\) cup of juice. How many cups of liquid is that in all?',
  'frac.p.ribbon': 'Jo has \\({T1}\\) of a yard of ribbon and cuts off \\({T2}\\) of a yard. How much ribbon is left, in yards?',
  'frac.h1': 'You can only add or subtract pieces of the same size. Find a common denominator first.',
  'frac.h2': 'The smallest number that both {d1} and {d2} go into is {L}. Use {L} as the denominator.',
  'frac.h3': 'Rewrite \\({T1}\\) as \\({s1}\\) and \\({T2}\\) as \\({s2}\\). Then work with the tops.',
  'frac.s1': 'Find a common denominator. The smallest number that both {d1} and {d2} go into is {L}.',
  'frac.s2': 'Rewrite both fractions with denominator {L}: \\({T1} = {s1}\\) and \\({T2} = {s2}\\).',
  'frac.s3add': 'Add the tops and keep the bottom: \\({a} + {b} = {r}\\).',
  'frac.s3sub': 'Subtract the tops and keep the bottom: \\({a} - {b} = {r}\\).',
  'frac.s4': 'Simplify: \\({r} = {ans}\\).',
  'g5-fraction-sum.mc.added-tops-and-bottoms': 'It looks like you added the tops and added the bottoms. Pieces of different sizes cannot be counted together. Rename both fractions with a common denominator first, then add only the tops.',
  'g5-fraction-sum.mc.subtracted-tops-and-bottoms': 'It looks like you subtracted the tops and subtracted the bottoms. The bottom tells the size of the pieces, and it stays the same. Rename both fractions with a common denominator first.',
  'g5-fraction-sum.mc.forgot-to-rename-the-tops': 'You found the common denominator, but the tops have to change too. When you cut each piece into smaller pieces, you get more pieces. Multiply the top by the same number as the bottom.',

  /* ---- G8: linear equations ---- */
  'lin.lv1': 'One step: add or subtract a number. Example: x + 4 = 9.',
  'lin.lv2': 'One step: multiply to undo a division, or divide. Example: 3x = 21.',
  'lin.lv3': 'Two steps. Example: 2x + 3 = 11.',
  'lin.lv4': 'Variables on both sides. Example: 5x + 2 = 2x + 14.',
  'lin.lv5': 'Brackets that need distributing. Example: 3(x + 2) = 18.',
  'lin.lv6': 'Brackets and variables on both sides, with negatives.',
  'lin.p.solve': 'Solve for \\(x\\). \\({eq}\\)',
  'lin.w.add': 'I think of a number and add {b}. The result is {d}. What is the number?',
  'lin.w.sub': 'I think of a number and subtract {b}. The result is {d}. What is the number?',
  'lin.w.mul': 'I think of a number and multiply it by {a}. The result is {d}. What is the number?',
  'lin.w.muladd': 'I think of a number, multiply it by {a}, then add {b}. The result is {d}. What is the number?',
  'lin.w.mulsub': 'I think of a number, multiply it by {a}, then subtract {b}. The result is {d}. What is the number?',
  'lin.h1.one': 'Get x alone. Do the opposite of what was done to x.',
  'lin.h1.paren': 'First get rid of the brackets by distributing. Then get x alone.',
  'lin.h1.both': 'Collect the x terms on one side and the plain numbers on the other, then divide.',
  'lin.h2.distribute': 'Distribute {a}: multiply it by every term inside the brackets.',
  'lin.h2.move': '{op} {t} on both sides.',
  'lin.h2.divide': 'Divide both sides by {A}.',
  'lin.s.distribute': 'Distribute {a} to both terms inside the brackets: \\({eq}\\).',
  'lin.s.xterm': '{op} \\({t}\\) on both sides to collect the x terms: \\({eq}\\).',
  'lin.s.const': '{op} {t} on both sides to get the x term alone: \\({eq}\\).',
  'lin.s.divide': 'Divide both sides by {A}: \\(x = {ans}\\).',
  'lin.s.done': 'So \\(x = {ans}\\).',
  'g8-linear-equation.mc.moved-the-number-with-the-wrong-sign': 'It looks like you added when you should have subtracted (or the other way round). To undo +b, subtract b from both sides. To undo -b, add b.',
  'g8-linear-equation.mc.multiplied-only-the-first-term': 'It looks like you multiplied only the first term inside the brackets. The number outside multiplies every term inside.',
  'g8-linear-equation.mc.moved-the-x-term-with-the-wrong-sign': 'It looks like the x terms were combined with the wrong sign. To move a term to the other side, do the opposite: subtract if it was added, add if it was subtracted.',
  'g8-linear-equation.mc.divided-only-one-term': 'It looks like you divided only one term by the number in front of x. Subtract the plain number first, then divide the whole right side.',
  'g8-linear-equation.mc.forgot-to-divide': 'It looks like the last step is missing. After you move the plain number, divide both sides by the number in front of x.',
  'g8-linear-equation.mc.subtracted-instead-of-dividing': 'It looks like you subtracted. The number in front of x multiplies it, so the opposite is to divide.',

  /* ---- G8: Pythagorean theorem ---- */
  'pyth.lv1': 'Find the hypotenuse of a small right triangle, like 3 and 4.',
  'pyth.lv2': 'Find the hypotenuse when the sides are multiples, like 6 and 8.',
  'pyth.lv3': 'Find a missing leg.',
  'pyth.lv4': 'Find any missing side in larger triangles.',
  'pyth.lv5': 'Real situations: ladders, screens and wires.',
  'pyth.p.hyp': 'A right triangle has legs of length {a} and {b}. How long is the hypotenuse?',
  'pyth.p.leg': 'A right triangle has a hypotenuse of length {c} and one leg of length {a}. How long is the other leg?',
  'pyth.p.ladder': 'A {c} foot ladder leans against a wall. The foot of the ladder is {a} feet from the wall. How high up the wall does the ladder reach, in feet?',
  'pyth.p.tv': 'A TV screen is {a} inches wide and {b} inches tall. How long is its diagonal, in inches?',
  'pyth.p.wire': 'A pole is {a} metres tall. A wire runs from its top to a point on the ground {b} metres from the base of the pole. How long is the wire, in metres?',
  'pyth.h1.hyp': 'The hypotenuse is the side across from the right angle. Use a squared plus b squared equals c squared.',
  'pyth.h1.leg': 'The hypotenuse is the longest side, across from the right angle. Put it in as c, then solve for the missing leg.',
  'pyth.s.theorem': 'In a right triangle, \\(a^2 + b^2 = c^2\\), where c is the hypotenuse.',
  'pyth.s.hyp1': 'Put in the legs: \\({a}^2 + {b}^2 = c^2\\).',
  'pyth.s.hyp2': 'Square them: \\({a2} + {b2} = {sum}\\), so \\(c^2 = {sum}\\).',
  'pyth.s.hyp3': 'Take the square root: \\(c = \\sqrt{{sum}} = {ans}\\).',
  'pyth.s.leg1': 'Put in the known leg and the hypotenuse: \\({k}^2 + u^2 = {c}^2\\), where u is the missing leg.',
  'pyth.s.leg2': 'Square them: \\({k2} + u^2 = {c2}\\).',
  'pyth.s.leg3': 'Subtract {k2} from both sides: \\(u^2 = {c2} - {k2} = {diff}\\).',
  'pyth.s.leg4': 'Take the square root: \\(u = \\sqrt{{diff}} = {ans}\\).',
  'g8-pythagorean-side.mc.added-the-legs': 'It looks like you added the two leg lengths. The hypotenuse is not the sum of the legs. Square each leg, add the squares, then take the square root.',
  'g8-pythagorean-side.mc.forgot-the-square-root': 'You found the square of the side. The last step is to take the square root to get the length.',
  'g8-pythagorean-side.mc.subtracted-the-lengths': 'It looks like you subtracted the lengths. Subtract the squares instead, then take the square root.',

  /* ---- A1: systems of two linear equations ---- */
  'sys.lv1': 'One equation is already solved for y. Substitute.',
  'sys.lv2': 'Both equations in standard form. The y terms are opposites, so adding removes y.',
  'sys.lv3': 'Multiply one equation first, then add or subtract.',
  'sys.lv4': 'Multiply both equations before you eliminate.',
  'sys.lv5': 'Negative coefficients and negative solutions.',
  'sys.p.solve': 'Solve the system. Give the answer as a pair \\((x, y)\\).<div class="pr-eq">\\({e1}\\)</div><div class="pr-eq">\\({e2}\\)</div>',
  'sys.h1.sub': 'One equation says what y equals. Put that expression in place of y in the other equation.',
  'sys.h1.elim': 'Make the y terms match, or be opposites, by multiplying. Then add or subtract the equations to remove y.',
  'sys.s.sub1': 'The first equation says \\({rhs}\\). Put that in place of y in the second equation: \\({eq}\\).',
  'sys.s.sub2': 'Combine like terms: \\({eq}\\).',
  'sys.s.sub3': 'Solve for x: \\({eq}\\), so \\(x = {x}\\).',
  'sys.s.sub4': 'Find y from the first equation: \\({calc}\\).',
  'sys.s.done': 'The solution is \\(({x}, {y})\\).',
  'sys.s.pick': 'Remove y. The y numbers are {b1} and {b2}. The smallest size that both fit into is {L}.',
  'sys.s.keep': 'The y terms already match in size: \\({e1}\\) and \\({e2}\\).',
  'sys.s.scale': 'Multiply equation 1 by {m1} and equation 2 by {m2} so the y terms match in size: \\({e1}\\) and \\({e2}\\).',
  'sys.s.add': 'The y terms are opposites. Add the equations: \\({eq}\\), so \\(x = {x}\\).',
  'sys.s.subtract': 'The y terms are the same. Subtract the equations: \\({eq}\\), so \\(x = {x}\\).',
  'sys.s.back': 'Put \\(x = {x}\\) into equation 1. That leaves \\({eq}\\), so \\(y = {y}\\).',
  'a1-system-solve.mc.swapped-the-order': 'You have the right two numbers, but in the wrong order. A pair is written (x, y): x first.',
  'a1-system-solve.mc.sign-slip-on-y': 'Your x is right, but check the sign of y when you put x back in.',
  'a1-system-solve.mc.sign-slip-on-x': 'Your y is right, but check the sign of x. Look at the step where x came from.'
};
