/* =====================================================================
   PRACTICE (strings): every sentence a student sees from the practice generators, keyed, with {slots}.
   Nothing is written into the logic, so a translation is a copy of this table. TeX is in String.raw-style
   double-backslash form inside normal strings. Do not put a literal {word} in TeX: {word} is a slot.
   ===================================================================== */
Practice.T = {
  /* ---- answer formats (shown under the answer box) ---- */
  'ans.whole': 'Enter a whole number.',
  'ans.number': 'Enter a number. You can write a whole number, a decimal, or a fraction like 3/4.',
  'ans.fraction': 'Enter a fraction in simplest form, like 5/6. A mixed number like 1 1/6 or a decimal that ends is fine too.',
  'ans.length': 'Enter a number. You may add the unit if you like.',
  'ans.pair': 'Enter the pair as (x, y), for example (2, -1).',
  'word.add': 'Add',
  'word.subtract': 'Subtract',
  'form.simplify': 'That value is right, but the fraction is not in simplest form. Divide the top and bottom by the same number, then enter it again.',

  /* ---- G4: multiplying multi-digit numbers ---- */
  'mult.lv1': 'A two-digit number times a one-digit number, small.',
  'mult.lv2': 'A two-digit number times a one-digit number, up to 99 by 9.',
  'mult.lv3': 'A three-digit number times a one-digit number.',
  'mult.lv4': 'Two two-digit numbers, small.',
  'mult.lv5': 'Two two-digit numbers, up to 99 by 99.',
  'mult.lv6': 'A three-digit number times a two-digit number.',
  'mult.p.eq': 'Find \\({a} \\times {b}\\).',
  'mult.p.chairs': 'A hall has {a} rows of chairs with {b} chairs in each row. How many chairs are there in all?',
  'mult.p.boxes': 'One box holds {b} pencils. How many pencils are in {a} boxes?',
  'mult.h1': 'Draw an area model. Break each number into hundreds, tens and ones, and multiply the pieces.',
  'mult.h2': 'Start with the first piece. {first}',
  'mult.h3': 'Here are all the pieces of the area model: {list}. Now add them.',
  'mult.s1': 'Break each number into place-value pieces: \\({a} = {pa}\\) and \\({b} = {pb}\\).',
  'mult.s1b': 'Break {a} into place-value pieces: \\({a} = {pa}\\). The other number, {b}, stays whole.',
  'mult.s2': 'Multiply each piece by each piece: {list}.',
  'mult.s3': 'Add the pieces: \\({sum}\\).',
  'g4-multiply.mc.missing-middle-pieces': 'It looks like you multiplied tens by tens and ones by ones only. An area model has four pieces. Do not forget tens times ones, and ones times tens.',
  'g4-multiply.mc.digits-without-place-value': 'It looks like you multiplied the digits as if each one meant just itself. A 4 in the tens place means 40. Multiply the whole pieces, like 40 times 5.',
  'g4-multiply.mc.left-out-the-ones-piece': 'It looks like one piece is missing. The ones digit also has to be multiplied, then added to the rest.',

  /* ---- G5: adding and subtracting fractions ---- */
  'frac.lv1': 'Add two fractions when one denominator is a multiple of the other. The sum is less than 1.',
  'frac.lv2': 'Add two fractions with different denominators that share no factor. The sum is less than 1.',
  'frac.lv3': 'Add two fractions with unlike denominators. The sum can be more than 1.',
  'frac.lv4': 'Subtract fractions with unlike denominators.',
  'frac.lv5': 'Add or subtract with larger denominators that share a factor, like 6 and 4.',
  'frac.p.add': 'Add. \\({T1} + {T2}\\)',
  'frac.p.sub': 'Subtract. \\({T1} - {T2}\\)',
  'frac.p.pizza': 'Mia ate \\({T1}\\) of a pizza at lunch and \\({T2}\\) of the same pizza at dinner. How much of the pizza did she eat in all?',
  'frac.p.cups': 'A recipe uses \\({T1}\\) cup of milk and \\({T2}\\) cup of juice. How many cups of liquid is that in all?',
  'frac.p.ribbon': 'Jo has \\({T1}\\) of a yard of ribbon and cuts off \\({T2}\\) of a yard. How much ribbon is left, in yards?',
  'frac.h1': 'You can only add or subtract pieces of the same size. Find a common denominator first.',
  'frac.h2': 'The smallest number that both {d1} and {d2} go into is {L}. Use {L} as the denominator.',
  'frac.h3': 'Rewrite \\({T1}\\) as \\({s1}\\) and \\({T2}\\) as \\({s2}\\). Then work with the tops.',
  'frac.s1': 'Find a common denominator. The smallest number that both {d1} and {d2} go into is {L}.',
  'frac.s2': 'Rewrite both fractions with denominator {L}: \\({T1} = {s1}\\) and \\({T2} = {s2}\\).',
  'frac.s3add': 'Add the tops and keep the bottom: \\({a} + {b} = {r}\\).',
  'frac.s3sub': 'Subtract the tops and keep the bottom: \\({a} - {b} = {r}\\).',
  'frac.s4': 'Simplify: \\({r} = {ans}\\).',
  'g5-fraction-sum.mc.added-tops-and-bottoms': 'It looks like you added the tops and added the bottoms. Pieces of different sizes cannot be counted together. Rename both fractions with a common denominator first, then add only the tops.',
  'g5-fraction-sum.mc.subtracted-tops-and-bottoms': 'It looks like you subtracted the tops and subtracted the bottoms. The bottom tells the size of the pieces, and it stays the same. Rename both fractions with a common denominator first.',
  'g5-fraction-sum.mc.forgot-to-rename-the-tops': 'You found the common denominator, but the tops have to change too. When you cut each piece into smaller pieces, you get more pieces. Multiply the top by the same number as the bottom.',

  /* ---- G8: linear equations ---- */
  'lin.lv1': 'One step: add or subtract a number. Example: x + 4 = 9.',
  'lin.lv2': 'One step: multiply to undo a division, or divide. Example: 3x = 21.',
  'lin.lv3': 'Two steps. Example: 2x + 3 = 11.',
  'lin.lv4': 'Variables on both sides. Example: 5x + 2 = 2x + 14.',
  'lin.lv5': 'Brackets that need distributing. Example: 3(x + 2) = 18.',
  'lin.lv6': 'Brackets and variables on both sides, with negatives.',
  'lin.p.solve': 'Solve for \\(x\\). \\({eq}\\)',
  'lin.w.add': 'I think of a number and add {b}. The result is {d}. What is the number?',
  'lin.w.sub': 'I think of a number and subtract {b}. The result is {d}. What is the number?',
  'lin.w.mul': 'I think of a number and multiply it by {a}. The result is {d}. What is the number?',
  'lin.w.muladd': 'I think of a number, multiply it by {a}, then add {b}. The result is {d}. What is the number?',
  'lin.w.mulsub': 'I think of a number, multiply it by {a}, then subtract {b}. The result is {d}. What is the number?',
  'lin.h1.one': 'Get x alone. Do the opposite of what was done to x.',
  'lin.h1.paren': 'First get rid of the brackets by distributing. Then get x alone.',
  'lin.h1.both': 'Collect the x terms on one side and the plain numbers on the other, then divide.',
  'lin.h2.distribute': 'Distribute {a}: multiply it by every term inside the brackets.',
  'lin.h2.move': '{op} {t} on both sides.',
  'lin.h2.divide': 'Divide both sides by {A}.',
  'lin.s.distribute': 'Distribute {a} to both terms inside the brackets: \\({eq}\\).',
  'lin.s.xterm': '{op} \\({t}\\) on both sides to collect the x terms: \\({eq}\\).',
  'lin.s.const': '{op} {t} on both sides to get the x term alone: \\({eq}\\).',
  'lin.s.divide': 'Divide both sides by {A}: \\(x = {ans}\\).',
  'lin.s.done': 'So \\(x = {ans}\\).',
  'g8-linear-equation.mc.moved-the-number-with-the-wrong-sign': 'It looks like you added when you should have subtracted (or the other way round). To undo +b, subtract b from both sides. To undo -b, add b.',
  'g8-linear-equation.mc.multiplied-only-the-first-term': 'It looks like you multiplied only the first term inside the brackets. The number outside multiplies every term inside.',
  'g8-linear-equation.mc.moved-the-x-term-with-the-wrong-sign': 'It looks like the x terms were combined with the wrong sign. To move a term to the other side, do the opposite: subtract if it was added, add if it was subtracted.',
  'g8-linear-equation.mc.divided-only-one-term': 'It looks like you divided only one term by the number in front of x. Subtract the plain number first, then divide the whole right side.',
  'g8-linear-equation.mc.forgot-to-divide': 'It looks like the last step is missing. After you move the plain number, divide both sides by the number in front of x.',
  'g8-linear-equation.mc.subtracted-instead-of-dividing': 'It looks like you subtracted. The number in front of x multiplies it, so the opposite is to divide.',

  /* ---- G8: Pythagorean theorem ---- */
  'pyth.lv1': 'Find the hypotenuse of a small right triangle, like 3 and 4.',
  'pyth.lv2': 'Find the hypotenuse when the sides are multiples, like 6 and 8.',
  'pyth.lv3': 'Find a missing leg.',
  'pyth.lv4': 'Find any missing side in larger triangles.',
  'pyth.lv5': 'Real situations: ladders, screens and wires.',
  'pyth.p.hyp': 'A right triangle has legs of length {a} and {b}. How long is the hypotenuse?',
  'pyth.p.leg': 'A right triangle has a hypotenuse of length {c} and one leg of length {a}. How long is the other leg?',
  'pyth.p.ladder': 'A {c} foot ladder leans against a wall. The foot of the ladder is {a} feet from the wall. How high up the wall does the ladder reach, in feet?',
  'pyth.p.tv': 'A TV screen is {a} inches wide and {b} inches tall. How long is its diagonal, in inches?',
  'pyth.p.wire': 'A pole is {a} metres tall. A wire runs from its top to a point on the ground {b} metres from the base of the pole. How long is the wire, in metres?',
  'pyth.h1.hyp': 'The hypotenuse is the side across from the right angle. Use a squared plus b squared equals c squared.',
  'pyth.h1.leg': 'The hypotenuse is the longest side, across from the right angle. Put it in as c, then solve for the missing leg.',
  'pyth.s.theorem': 'In a right triangle, \\(a^2 + b^2 = c^2\\), where c is the hypotenuse.',
  'pyth.s.hyp1': 'Put in the legs: \\({a}^2 + {b}^2 = c^2\\).',
  'pyth.s.hyp2': 'Square them: \\({a2} + {b2} = {sum}\\), so \\(c^2 = {sum}\\).',
  'pyth.s.hyp3': 'Take the square root: \\(c = \\sqrt{{sum}} = {ans}\\).',
  'pyth.s.leg1': 'Put in the known leg and the hypotenuse: \\({k}^2 + u^2 = {c}^2\\), where u is the missing leg.',
  'pyth.s.leg2': 'Square them: \\({k2} + u^2 = {c2}\\).',
  'pyth.s.leg3': 'Subtract {k2} from both sides: \\(u^2 = {c2} - {k2} = {diff}\\).',
  'pyth.s.leg4': 'Take the square root: \\(u = \\sqrt{{diff}} = {ans}\\).',
  'g8-pythagorean-side.mc.added-the-legs': 'It looks like you added the two leg lengths. The hypotenuse is not the sum of the legs. Square each leg, add the squares, then take the square root.',
  'g8-pythagorean-side.mc.forgot-the-square-root': 'You found the square of the side. The last step is to take the square root to get the length.',
  'g8-pythagorean-side.mc.subtracted-the-lengths': 'It looks like you subtracted the lengths. Subtract the squares instead, then take the square root.',

  /* ---- A1: systems of two linear equations ---- */
  'sys.lv1': 'One equation is already solved for y. Substitute.',
  'sys.lv2': 'Both equations in standard form. The y terms are opposites, so adding removes y.',
  'sys.lv3': 'Multiply one equation first, then add or subtract.',
  'sys.lv4': 'Multiply both equations before you eliminate.',
  'sys.lv5': 'Negative coefficients and negative solutions.',
  'sys.p.solve': 'Solve the system. Give the answer as a pair \\((x, y)\\).<div class="pr-eq">\\({e1}\\)</div><div class="pr-eq">\\({e2}\\)</div>',
  'sys.h1.sub': 'One equation says what y equals. Put that expression in place of y in the other equation.',
  'sys.h1.elim': 'Make the y terms match, or be opposites, by multiplying. Then add or subtract the equations to remove y.',
  'sys.s.sub1': 'The first equation says \\({rhs}\\). Put that in place of y in the second equation: \\({eq}\\).',
  'sys.s.sub2': 'Combine like terms: \\({eq}\\).',
  'sys.s.sub3': 'Solve for x: \\({eq}\\), so \\(x = {x}\\).',
  'sys.s.sub4': 'Find y from the first equation: \\({calc}\\).',
  'sys.s.done': 'The solution is \\(({x}, {y})\\).',
  'sys.s.pick': 'Remove y. The y numbers are {b1} and {b2}. The smallest size that both fit into is {L}.',
  'sys.s.keep': 'The y terms already match in size: \\({e1}\\) and \\({e2}\\).',
  'sys.s.scale': 'Multiply equation 1 by {m1} and equation 2 by {m2} so the y terms match in size: \\({e1}\\) and \\({e2}\\).',
  'sys.s.add': 'The y terms are opposites. Add the equations: \\({eq}\\), so \\(x = {x}\\).',
  'sys.s.subtract': 'The y terms are the same. Subtract the equations: \\({eq}\\), so \\(x = {x}\\).',
  'sys.s.back': 'Put \\(x = {x}\\) into equation 1. That leaves \\({eq}\\), so \\(y = {y}\\).',
  'a1-system-solve.mc.swapped-the-order': 'You have the right two numbers, but in the wrong order. A pair is written (x, y): x first.',
  'a1-system-solve.mc.sign-slip-on-y': 'Your x is right, but check the sign of y when you put x back in.',
  'a1-system-solve.mc.sign-slip-on-x': 'Your y is right, but check the sign of x. Look at the step where x came from.',
  /* ---- more answer formats ---- */
  'ans.decimal': 'Enter a decimal, like 2.87. A fraction is fine too.',
  'ans.integer': 'Enter a whole number. Use a minus sign for a negative number, like -4.',
  'ans.percent': 'Enter the percent as a number, like 25. The % sign is optional.',

  /* ---- G4: division ---- */
  'div.lv1': 'A two-digit number divided by 2 to 5. No remainder.',
  'div.lv2': 'A three-digit number divided by 2 to 5. No remainder.',
  'div.lv3': 'A three-digit number divided by 6 to 9. No remainder.',
  'div.lv4': 'A four-digit number divided by a one-digit number. No remainder.',
  'div.lv5': 'Quotients with a zero inside, like 4 0 5.',
  'div.p.eq': 'Find \\({a} \\div {d}\\).',
  'div.p.stickers': 'There are {a} stickers. They are shared equally among {d} children. How many stickers does each child get?',
  'div.p.boxes': 'A box holds {d} crayons. How many boxes are needed to hold {a} crayons?',
  'div.h1': 'Ask: how many groups of {d} fit? Break the answer into place-value pieces: hundreds, tens and ones.',
  'div.h2': 'Try {p} groups first. \\({d} \\times {p} = {prod}\\). That leaves {left} still to divide.',
  'div.h3': 'The answer is the sum of these pieces: {list}.',
  'div.s1': 'Find pieces of the answer. For each piece, multiply by {d}: {list}.',
  'div.s2': 'Check that the products add up to the number you started with: \\({sum} = {a}\\).',
  'div.s3': 'So \\({a} \\div {d} = {sum} = {q}\\).',
  'g4-divide.mc.multiplied-instead-of-dividing': 'It looks like you multiplied. Dividing is splitting into equal groups, so the answer is smaller than the number you start with.',
  'g4-divide.mc.subtracted-instead-of-dividing': 'It looks like you subtracted. Ask instead how many groups of the divisor fit into the number.',
  'g4-divide.mc.answer-ten-times-too-big': 'Your digits are right, but the answer is ten times too big. Estimate first: about how many groups should you get? Then check each place.',
  'g4-divide.mc.dropped-the-zero': 'It looks like a zero was left out. A zero in the answer holds a place. Without it the digits slide into the wrong places.',

  /* ---- G4: rectangles ---- */
  'rect.lv1': 'Find the area of a small rectangle.',
  'rect.lv2': 'Find the perimeter of a small rectangle.',
  'rect.lv3': 'Area or perimeter of a larger rectangle.',
  'rect.lv4': 'Find a missing side from the area.',
  'rect.lv5': 'Find a missing side from the perimeter.',
  'rect.p.area': 'A rectangle is {l} {u} long and {w} {u} wide. What is its area, in square {u}?',
  'rect.p.perim': 'A rectangle is {l} {u} long and {w} {u} wide. What is its perimeter, in {u}?',
  'rect.p.missA': 'A rectangle has an area of {A} square {u} and is {w} {u} wide. How long is it, in {u}?',
  'rect.p.missP': 'A rectangle has a perimeter of {P} {u} and is {l} {u} long. How wide is it, in {u}?',
  'rect.c.area.q': 'Area = ?',
  'rect.c.perim.q': 'Perimeter = ?',
  'rect.c.area': 'Area = {A}',
  'rect.c.perim': 'Perimeter = {P}',
  'rect.h1.area': 'Area counts the squares inside. Multiply the length by the width.',
  'rect.h2.area': 'Multiply \\({l} \\times {w}\\).',
  'rect.h1.perim': 'Perimeter is the distance around. Add up all four sides.',
  'rect.h2.perim': 'A rectangle has two sides of {l} and two sides of {w}.',
  'rect.h1.missA': 'Area is length times width. Work backward: divide the area by the side you know.',
  'rect.h2.missA': 'Divide \\({A} \\div {w}\\).',
  'rect.h1.missP': 'The perimeter is two lengths plus two widths. Take away the two lengths you know, then split what is left between the two widths.',
  'rect.h2.missP': 'Two lengths make 2 \\(\\times\\) {l}. Subtract that from {P}.',
  'rect.s.area': 'Area = length \\(\\times\\) width, so \\({l} \\times {w} = {A}\\).',
  'rect.s.perim1': 'Add one length and one width: \\({l} + {w} = {s}\\).',
  'rect.s.perim2': 'A rectangle has two of each, so double it: \\(2 \\times {s} = {P}\\).',
  'rect.s.missA1': 'Area = length \\(\\times\\) width, so length = area \\(\\div\\) width.',
  'rect.s.missA2': '\\({A} \\div {w} = {l}\\).',
  'rect.s.missP1': 'The two lengths use up \\(2 \\times {l}\\). What is left for the two widths is \\({P} - 2 \\times {l} = {rest}\\).',
  'rect.s.missP2': 'Split it between two widths: \\({rest} \\div 2 = {w}\\).',
  'g4-rectangle.mc.added-instead-of-multiplying': 'It looks like you added the length and the width. Area counts squares inside, so multiply.',
  'g4-rectangle.mc.found-the-perimeter': 'It looks like you found the perimeter, the distance around. Area is the space inside: length times width.',
  'g4-rectangle.mc.added-just-two-sides': 'It looks like you added only two sides. A rectangle has four sides: two lengths and two widths.',
  'g4-rectangle.mc.found-the-area': 'It looks like you found the area. Perimeter is the distance around, so add the sides.',
  'g4-rectangle.mc.multiplied-instead-of-dividing': 'It looks like you multiplied. To find a missing side from the area, divide the area by the side you know.',
  'g4-rectangle.mc.subtracted-instead-of-dividing': 'It looks like you subtracted. Area is length times width, so the opposite is to divide.',
  'g4-rectangle.mc.forgot-to-halve': 'You found what is left for the two widths, but there are two of them. Split it in half.',
  'g4-rectangle.mc.took-away-only-one-length': 'It looks like you took away only one length. A rectangle has two lengths, so take away both.',

  /* ---- G5: decimals ---- */
  'dec.lv1': 'Add tenths, like 0.3 + 0.4.',
  'dec.lv2': 'Add hundredths, like 0.25 + 0.36.',
  'dec.lv3': 'Add decimals with different numbers of places, like 2.5 + 0.37.',
  'dec.lv4': 'Subtract decimals, including from a whole number.',
  'dec.lv5': 'Add or subtract up to thousandths.',
  'dec.unit1': 'tenths',
  'dec.unit2': 'hundredths',
  'dec.unit3': 'thousandths',
  'dec.p.add': 'Add. \\({a} + {b}\\)',
  'dec.p.sub': 'Subtract. \\({a} - {b}\\)',
  'dec.p.run': 'Sam ran {a} miles on Monday and {b} miles on Tuesday. How many miles did he run in all?',
  'dec.p.board': 'A board is {a} meters long. A piece {b} meters long is cut off. How long is the rest, in meters?',
  'dec.h1': 'Line up the decimal points, so tenths sit under tenths and hundredths under hundredths. Add zeros to fill in the empty places.',
  'dec.h2': 'Give both numbers the same number of decimal places: \\({A}\\) and \\({B}\\).',
  'dec.s1': 'Give both numbers the same number of decimal places: \\({A}\\) and \\({B}\\). The places now line up.',
  'dec.s2add': 'Think of them as {unit}. Add: \\({sa} + {sb} = {top}\\) {unit}.',
  'dec.s2sub': 'Think of them as {unit}. Subtract: \\({sa} - {sb} = {top}\\) {unit}.',
  'dec.s3': '{top} {unit} is written \\({ans}\\).',
  'g5-decimals.mc.added-as-whole-numbers': 'It looks like you added the digits as if the decimal points were not there. Line up the places first: tenths with tenths, hundredths with hundredths.',
  'g5-decimals.mc.misplaced-the-decimal-point': 'Your digits are right, but the decimal point is one place off. Estimate first: is the answer about as big as you expect?',

  /* ---- G5: order of operations ---- */
  'oo.lv1': 'Two operations, no brackets.',
  'oo.lv2': 'Division and subtraction.',
  'oo.lv3': 'Brackets.',
  'oo.lv4': 'Three operations.',
  'oo.lv5': 'Several brackets and operations.',
  'oo.p': 'Evaluate. \\({tex}\\)',
  'oo.h1': 'Order: brackets first, then multiply and divide from left to right, then add and subtract from left to right.',
  'oo.h2': 'Start with {first}',
  'oo.first.brackets': 'whatever is inside the brackets.',
  'oo.first.muldiv': 'the multiplication or division.',
  'oo.first.addsub': 'the addition or subtraction.',
  'oo.s.unbracket': 'The brackets only hold one number now: \\({expr}\\).',
  'oo.s.brackets-muldiv': 'Brackets first. Inside them, multiply or divide first: \\({expr}\\).',
  'oo.s.brackets-addsub': 'Brackets first. Work inside them: \\({expr}\\).',
  'oo.s.muldiv': 'Multiply or divide before adding or subtracting: \\({expr}\\).',
  'oo.s.addsub': 'Now add or subtract: \\({expr}\\).',
  'g5-order-of-operations.mc.went-left-to-right': 'It looks like you worked straight from left to right. Multiplication and division come before addition and subtraction.',
  'g5-order-of-operations.mc.ignored-the-brackets': 'It looks like the brackets were skipped. Whatever is inside brackets is done first.',

  /* ---- G7: integers ---- */
  'int.lv1': 'Add a positive and a negative number.',
  'int.lv2': 'Subtract to land below zero.',
  'int.lv3': 'Negative numbers added and subtracted, including subtracting a negative.',
  'int.lv4': 'Any signs, bigger numbers.',
  'int.lv5': 'Three terms.',
  'int.p.eval': 'Work it out. \\({tex}\\)',
  'int.p.rise': 'The temperature is {a} degrees. It rises {b} degrees. What is the new temperature?',
  'int.p.fall': 'The temperature is {a} degrees. It falls {b} degrees. What is the new temperature?',
  'int.right': 'right',
  'int.left': 'left',
  'int.h1': 'Picture a number line. Adding a positive moves right. Adding a negative moves left. Subtracting does the opposite.',
  'int.h2': 'Start at {acc}. Move {dir} {n}.',
  'int.s.flip': 'Subtracting \\({t}\\) is the same as adding {n}, so the move reverses.',
  'int.s.move': 'Start at \\({acc}\\). Move {dir} {n}. You land on \\({res}\\).',
  'g7-integers.mc.sign-of-the-answer-flipped': 'You have the right size but the wrong sign. Check which way you moved on the number line, and whether you ended up above or below zero.',
  'g7-integers.mc.ignored-the-negative-signs': 'It looks like the negative signs were ignored. A negative number sits left of zero, and that changes which way you move.',
  'g7-integers.mc.subtracting-a-negative-as-a-plain-subtract': 'It looks like subtracting a negative was treated like subtracting a positive. Taking away a negative is the same as adding the positive.',

  /* ---- G6: percent ---- */
  'pct.lv1': 'Percent of a number: 10%, 25% and 50%.',
  'pct.lv2': 'Percent of a number: multiples of 10%.',
  'pct.lv3': 'Percent of a number: 5%, 15%, 35%, 45% and 75%.',
  'pct.lv4': 'Find what percent one number is of another.',
  'pct.lv5': 'Find the whole when you know the part and the percent.',
  'pct.p.of': 'What is {p}% of {n}?',
  'pct.p.class': 'A class has {n} students. {p}% of them walk to school. How many students walk?',
  'pct.p.shirt': 'A shirt costs {n} dollars. It is on sale for {p}% off. How many dollars does the sale take off?',
  'pct.p.what': 'What percent of {n} is {part}?',
  'pct.p.walk': 'A class has {n} students. {part} of them walk to school. What percent of the class walks?',
  'pct.p.whole': '{part} is {p}% of what number?',
  'pct.p.sale': 'A jacket is on sale for {p}% off, which takes off {part} dollars. What was the original price, in dollars?',
  'pct.h1.of': 'Percent means out of 100. Write the percent as a fraction over 100, then multiply.',
  'pct.h2.of': 'Multiply \\({n} \\times \\frac{{p}}{100}\\).',
  'pct.h1.pc': 'Write the part over the whole as a fraction, then make the bottom 100.',
  'pct.h2.pc': 'Start with \\(\\frac{{part}}{{n}}\\).',
  'pct.h1.wh': 'The percent tells how many hundredths the part is. Work backward from the part to the whole.',
  'pct.h2.wh': '{p}% means \\(\\frac{{p}}{100}\\) of the whole is {part}. What number times \\(\\frac{{p}}{100}\\) gives {part}?',
  'pct.s.of1': '{p}% means {p} out of 100, which is \\(\\frac{{p}}{100}\\).',
  'pct.s.of2': 'Multiply: \\({n} \\times \\frac{{p}}{100} = {frac} = {part}\\).',
  'pct.s.pc1': 'Write the part over the whole: \\(\\frac{{part}}{{n}}\\).',
  'pct.s.pc2': 'Rewrite it with 100 on the bottom: it equals \\(\\frac{{p}}{100}\\).',
  'pct.s.pc3': 'Out of 100 means percent, so it is {p}%.',
  'pct.s.wh1': '{p}% of the whole is {part}. So {part} is \\(\\frac{{p}}{100}\\) of the whole.',
  'pct.s.wh2': 'Divide by the fraction: \\({part} \\div \\frac{{p}}{100} = {part} \\times \\frac{100}{{p}} = {n}\\).',
  'g6-percent.mc.forgot-to-divide-by-100': 'It looks like the last step is missing. Percent means out of 100, so divide by 100 after you multiply.',
  'g6-percent.mc.divided-by-the-percent-number': 'It looks like you divided the number by the percent. Instead, write the percent as a fraction over 100 and multiply.',
  'g6-percent.mc.used-the-percent-as-the-answer': 'The percent is the rate, not the amount. Find that rate of the number.',
  'g6-percent.mc.inverted-the-fraction': 'It looks like the fraction is upside down. The percent is the part over the whole.',
  'g6-percent.mc.gave-the-decimal-not-the-percent': 'That fraction is right, but a percent is out of 100. Multiply by 100 to turn it into a percent.',
  'g6-percent.mc.gave-the-part-as-the-percent': 'That number is the part, not the percent. Compare the part with the whole.',
  'g6-percent.mc.found-the-percent-of-the-part': 'It looks like you found the percent of the part. The part is already the percent of the whole, so work backward.',
  'g6-percent.mc.divided-by-100-only': 'It looks like you only divided by 100. The part is only the percent of the whole, so divide it by that percent as a fraction.',
  'g6-percent.mc.used-the-percent-as-the-whole': 'The percent is not the whole. The whole is the number that the percent of is the part.',

  /* ---- G6: mean ---- */
  'mean.lv1': 'The mean of three small numbers.',
  'mean.lv2': 'The mean of four or five numbers.',
  'mean.lv3': 'The mean of five or six larger numbers.',
  'mean.lv4': 'Find a missing value from the mean.',
  'mean.lv5': 'The mean of six to eight values.',
  'mean.p.eq': 'Find the mean of this data set: {list}.',
  'mean.p.games': 'A player scored these points in {n} games: {list}. What is the mean number of points per game?',
  'mean.p.quiz': 'A student got these scores on {n} quizzes: {list}. What is the mean score?',
  'mean.p.missing': 'The mean of {n} test scores is {m}. All but one of the scores are {list}. What is the missing score?',
  'mean.h1': 'The mean shares the total equally. Add everything, then divide by how many values there are.',
  'mean.h2': 'Add all the values. Then divide the total by {n}.',
  'mean.h1.m': 'If you know the mean and how many values there are, you can find the total.',
  'mean.h2.m': 'Total = mean \\(\\times\\) count = \\({m} \\times {n}\\).',
  'mean.s.a1': 'Add all the values: \\({sum} = {total}\\).',
  'mean.s.a2': 'Divide by how many values there are: \\({total} \\div {n} = {m}\\).',
  'mean.s.m1': 'The total of all the scores is the mean times the count: \\({n} \\times {m} = {total}\\).',
  'mean.s.m2': 'The scores you know add to \\({sum} = {ks}\\).',
  'mean.s.m3': 'The missing score is what is left: \\({total} - {ks} = {x}\\).',
  'g6-mean.mc.forgot-to-divide': 'It looks like you stopped after adding. The mean shares the total equally, so divide by how many values there are.',
  'g6-mean.mc.divided-by-the-wrong-count': 'It looks like you divided by the wrong number. Count every value in the data set, then divide the total by that count.',
  'g6-mean.mc.gave-the-median': 'It looks like you gave the middle value. That is the median. The mean is the total shared equally.',
  'g6-mean.mc.found-the-mean-of-the-known-scores': 'It looks like you averaged only the scores you know. Use the mean of all the scores to find the total first.',
  'g6-mean.mc.forgot-to-subtract-the-known-scores': 'You found the total of all the scores. Now take away the scores you already know.',
  /* ---- more answer formats ---- */
  'ans.slope': 'Enter the slope as a whole number or a fraction in simplest form, like -2/3.',
  'ans.set': 'Enter every solution, separated by commas, like 2, 3. If there is just one solution, enter just that one.',
  'ans.degrees': 'Enter the number of degrees. The degree sign is optional.',
  'ans.pi': 'Give the answer as a multiple of pi. Enter just the number in front of pi.',

  /* ---- A1: slope ---- */
  'slope.lv1': 'Positive whole-number slopes.',
  'slope.lv2': 'Negative whole-number slopes.',
  'slope.lv3': 'Positive fraction slopes.',
  'slope.lv4': 'Negative fraction slopes, with negative coordinates.',
  'slope.lv5': 'Any slope, including zero, with points in any order.',
  'slope.p': 'Find the slope of the line through \\(({x1}, {y1})\\) and \\(({x2}, {y2})\\).',
  'slope.h1': 'Slope is rise over run: how far up (or down) divided by how far across.',
  'slope.h2': 'Rise: \\({y2} - {y1}\\). Run: \\({x2} - {x1}\\). Subtract in the same order on top and bottom.',
  'slope.s1': 'Rise (the change in y): \\({rise} = {r}\\).',
  'slope.s2': 'Run (the change in x): \\({run} = {n}\\).',
  'slope.s3': 'Slope = rise over run: \\(\\frac{{rise}}{{run}} = {m}\\).',
  'a1-slope.mc.run-over-rise': 'It looks like you divided run by rise. Slope is rise over run: the change in y goes on top.',
  'a1-slope.mc.subtracted-in-different-orders': 'It looks like the points were subtracted in different orders on top and bottom. Use the same point first both times, or the sign will flip.',
  'a1-slope.mc.added-the-coordinates': 'It looks like you added the coordinates. Slope compares how much y changes with how much x changes, so subtract.',

  /* ---- A1: functions ---- */
  'fn.lv1': 'Evaluate a linear function at a positive number.',
  'fn.lv2': 'Evaluate a linear function at a negative number.',
  'fn.lv3': 'Evaluate a quadratic function at a positive number.',
  'fn.lv4': 'Evaluate a quadratic function at a negative number.',
  'fn.lv5': 'Compose two linear functions: f of g of a number.',
  'fn.p.eval': 'Let \\(f(x) = {f}\\). Find \\(f({x})\\).',
  'fn.p.comp': 'Let \\(f(x) = {f}\\) and \\(g(x) = {g}\\). Find \\(f(g({k}))\\).',
  'fn.h1': 'Replace every x with the input, in brackets. Then work it out.',
  'fn.h2': 'Put {x} in place of each x. Brackets keep a negative number together.',
  'fn.h1.comp': 'Work from the inside out: find g first, then put that result into f.',
  'fn.s.sub': 'Replace x with the input: \\({expr}\\).',
  'fn.s.val': 'Work it out. The value is \\({v}\\).',
  'fn.s.inner': 'Inside first: \\(g({k}) = {g} = {v}\\).',
  'fn.s.outer': 'Now put {g} into f: \\(f({g}) = {f} = {v}\\).',
  'a1-evaluate-function.mc.composed-in-the-wrong-order': 'It looks like g and f were applied in the wrong order. In f of g, the inner function g goes first.',
  'a1-evaluate-function.mc.dropped-the-negative-sign': 'It looks like the negative sign was lost. Put the input in brackets, so -3 stays negative when you multiply or square it.',
  'a1-evaluate-function.mc.squared-without-the-brackets': 'It looks like only the 3 was squared, not -3. A negative number squared is positive: \\((-3)^2 = 9\\).',
  'a1-evaluate-function.mc.added-instead-of-multiplying': 'It looks like the numbers were added. A number written next to x means multiply.',

  /* ---- A1: quadratics ---- */
  'quad.lv1': 'Monic quadratics with two positive solutions.',
  'quad.lv2': 'One positive and one negative solution.',
  'quad.lv3': 'Any signs, a solution of zero, or a repeated solution.',
  'quad.lv4': 'A common factor in front, like 2x squared.',
  'quad.lv5': 'Leading coefficient not 1, with fraction solutions.',
  'quad.p': 'Solve by factoring. Give all solutions. \\({eq} = 0\\)',
  'quad.h1': 'Factor the left side into brackets. A product is zero only when one of its factors is zero.',
  'quad.h2': 'Find two numbers that multiply to {prod} and add to {sum}. Each solution is the opposite of one of them.',
  'quad.h2b': 'Look for brackets like (px + q)(rx + s). The x terms multiply to {a}x squared and the plain numbers multiply to {c}.',
  'quad.s.divide': 'Divide every term by {a}: \\({eq}\\).',
  'quad.s.factor': 'Factor: \\({fac}\\).',
  'quad.s.zero': 'A product is zero when a factor is zero, so \\({sol}\\).',
  'a1-quadratic-roots.mc.signs-of-the-solutions-reversed': 'It looks like the signs are the wrong way round. In (x - 2), the solution is x = 2, not -2: it is the number that makes the bracket zero.',
  'a1-quadratic-roots.mc.gave-only-one-solution': 'You found one solution. A quadratic can have two. Set each factor equal to zero.',
  'a1-quadratic-roots.mc.gave-the-coefficients': 'Those are the numbers in front of the terms, not the solutions. Factor first, then set each factor to zero.',
  'a1-quadratic-roots.mc.forgot-to-divide-by-the-coefficient': 'From (2x - 1) = 0 you get 2x = 1, so x = 1/2. Divide by the number in front of x.',

  /* ---- A1: sequences ---- */
  'seq.lv1': 'Arithmetic sequences that go up.',
  'seq.lv2': 'Arithmetic sequences that go down.',
  'seq.lv3': 'Find the common difference from two terms.',
  'seq.lv4': 'Geometric sequences.',
  'seq.lv5': 'Which term of an arithmetic sequence is a given value?',
  'seq.p.up': 'An arithmetic sequence starts at {a1} and goes up by {d} each time. What is term number {n}?',
  'seq.p.down': 'An arithmetic sequence starts at {a1} and goes down by {d} each time. What is term number {n}?',
  'seq.p.list': 'The sequence {list}, and so on, is arithmetic. What is term number {n}?',
  'seq.p.diff': 'In an arithmetic sequence, term number {i} is {ai} and term number {j} is {aj}. What is the common difference?',
  'seq.p.geom': 'A geometric sequence starts at {a1} and is multiplied by {r} each time. What is term number {n}?',
  'seq.p.which': 'An arithmetic sequence starts at {a1} and goes up by {d} each time. Which term number is equal to {an}?',
  'seq.h1.arith': 'Term 1 is the start. To reach term n you add the difference n minus 1 times.',
  'seq.h2.arith': 'You take {nm} steps to get from term 1 to term {n}.',
  'seq.h1.diff': 'The difference is how much the sequence changes in one step. Find the total change, then divide by the number of steps.',
  'seq.h2.diff': 'There are {g} steps between those two terms.',
  'seq.h1.geom': 'In a geometric sequence you multiply by the ratio each step. Term n is the start times the ratio, multiplied n minus 1 times.',
  'seq.h2.geom': 'The ratio is used {p} times.',
  'seq.h1.which': 'Find how far the value is above the start. Divide by the difference to count the steps. Then add 1, because term 1 is the start.',
  'seq.h2.which': 'The value is \\({an} - {a1}\\) above the start.',
  'seq.s.rule': 'Arithmetic rule: term n = first term + (n - 1) \\(\\times\\) difference.',
  'seq.s.arith': 'Term \\({n}\\): \\({a1} + ({n} - 1) \\times {d} = {v}\\).',
  'seq.s.gap': 'From term {i} to term {j} there are \\({j} - {i} = {g}\\) steps, and the value changes by \\({aj} - {ai} = {gap}\\).',
  'seq.s.diff': 'Each step changes it by \\({gap} \\div {g} = {d}\\).',
  'seq.s.rule.g': 'Geometric rule: term n = first term \\(\\times\\) ratio to the power (n - 1).',
  'seq.s.geom': '\\({a1} \\times {r}^{{p}} = {v}\\).',
  'seq.s.which1': 'The value is \\({an} - {a1} = {g}\\) above the start.',
  'seq.s.which2': 'That is \\({g} \\div {d} = {k}\\) steps after term 1, so it is term \\({k} + 1 = {n}\\).',
  'a1-sequence-term.mc.used-n-instead-of-n-minus-1': 'It looks like you added the difference n times. Term 1 is the start, so you only add it n minus 1 times.',
  'a1-sequence-term.mc.multiplied-the-first-term': 'It looks like the first term was multiplied. You add the difference repeatedly; you do not multiply the start.',
  'a1-sequence-term.mc.forgot-the-first-term': 'It looks like the starting number is missing. Start from term 1, then add the steps.',
  'a1-sequence-term.mc.forgot-to-divide-by-the-gap': 'That is the total change. Divide it by the number of steps between the two terms.',
  'a1-sequence-term.mc.divided-by-the-later-term-number': 'You divided by the term number. Divide by the number of steps between the two terms: the difference of the term numbers.',
  'a1-sequence-term.mc.used-the-power-n': 'It looks like the ratio was used n times. Term 1 is the start, so use the ratio n minus 1 times.',
  'a1-sequence-term.mc.multiplied-instead-of-using-a-power': 'It looks like you multiplied by the number of steps. Each step multiplies by the ratio again, which is a power of the ratio.',
  'a1-sequence-term.mc.added-the-ratio': 'It looks like the ratio was added. A geometric sequence multiplies by the ratio each step.',
  'a1-sequence-term.mc.forgot-to-add-one': 'That counts the steps after term 1. The term number is one more than the number of steps.',
  'a1-sequence-term.mc.divided-the-term-by-the-difference': 'It looks like you divided the value itself. First find how far it is above the start, then divide by the difference.',

  /* ---- Geometry: angles ---- */
  'ang.lv1': 'The third angle of a triangle.',
  'ang.lv2': 'Base angles of an isosceles triangle.',
  'ang.lv3': 'An exterior angle of a triangle.',
  'ang.lv4': 'The angle sum of a polygon, and one angle of a regular polygon.',
  'ang.lv5': 'A missing angle in a polygon.',
  'ang.p.tri': 'Two angles of a triangle are {A} degrees and {B} degrees. How big is the third angle, in degrees?',
  'ang.p.iso': 'An isosceles triangle has an apex angle of {apex} degrees. How big is each base angle, in degrees?',
  'ang.p.ext': 'A triangle has angles of {A} degrees and {B} degrees. What is the exterior angle at the third vertex, in degrees?',
  'ang.p.sum': 'What is the sum of the interior angles of a polygon with {n} sides, in degrees?',
  'ang.p.reg': 'What is each interior angle of a regular polygon with {n} sides, in degrees?',
  'ang.p.missing': 'A polygon with {n} sides has these interior angles, in degrees: {list}. One angle is missing. How big is it, in degrees?',
  'ang.h1.tri': 'The three angles of a triangle add up to 180 degrees.',
  'ang.h2.tri': 'Add the two angles you know: \\({A} + {B} = {s}\\). What is left of 180?',
  'ang.h1.iso': 'An isosceles triangle has two equal base angles. All three angles add up to 180 degrees.',
  'ang.h2.iso': 'The two base angles share \\(180 - {apex} = {rest}\\) degrees.',
  'ang.h1.ext': 'An exterior angle and the interior angle next to it make a straight line, 180 degrees. It also equals the sum of the two far-away interior angles.',
  'ang.h2.ext': 'Try adding the two angles you were given: \\({A} + {B}\\).',
  'ang.h1.poly': 'Split the polygon into triangles from one corner. Each triangle adds 180 degrees.',
  'ang.h1.reg': 'First find the sum of all the interior angles. Then share it equally, because every angle of a regular polygon is the same.',
  'ang.h2.poly': 'A polygon with {n} sides splits into \\({n} - 2 = {t}\\) triangles.',
  'ang.h1.miss': 'Find the total of all the interior angles, then subtract the ones you know.',
  'ang.h2.miss': 'A polygon with {n} sides has a total of {total} degrees.',
  'ang.s.sum': 'The angles of a triangle add up to 180 degrees.',
  'ang.s.tri': 'The two known angles add to \\({A} + {B} = {s}\\). The third is \\(180 - {s} = {C}\\).',
  'ang.s.iso1': 'The three angles add to 180, so the two base angles share \\(180 - {apex} = {rest}\\).',
  'ang.s.iso2': 'The base angles are equal, so each is \\({rest} \\div 2 = {base}\\).',
  'ang.s.ext1': 'The third interior angle is \\(180 - {A} - {B} = {C}\\).',
  'ang.s.ext2': 'The exterior angle makes a straight line with it: \\(180 - {C} = {e}\\). That is also \\({A} + {B}\\).',
  'ang.s.poly1': 'A polygon with {n} sides splits into \\({n} - 2 = {t}\\) triangles.',
  'ang.s.poly2': 'Each triangle has 180 degrees: \\({t} \\times 180 = {s}\\).',
  'ang.s.reg': 'All the angles are equal, so each is \\({s} \\div {n} = {a}\\).',
  'ang.s.miss': 'The angles add to \\({total}\\). The known angles add to \\({sum} = {ks}\\). The missing angle is \\({total} - {ks} = {left}\\).',
  'geo-angles.mc.added-the-two-angles': 'It looks like you added the two angles and stopped. That is the part of the 180 degrees that is used. The third angle is what is left.',
  'geo-angles.mc.used-360': 'It looks like you used 360. The angles of a triangle add to 180 degrees. 360 is for a quadrilateral.',
  'geo-angles.mc.forgot-to-halve': 'That is the total of the two base angles. They are equal, so each one is half of it.',
  'geo-angles.mc.treated-the-apex-as-a-base-angle': 'It looks like the apex angle was counted as a base angle. In an isosceles triangle, the two equal angles are at the base.',
  'geo-angles.mc.gave-the-interior-angle': 'That is the interior angle at the third vertex. The exterior angle is on the outside, and together they make 180.',
  'geo-angles.mc.used-only-one-angle': 'The exterior angle equals the sum of both far-away interior angles, not just one.',
  'geo-angles.mc.forgot-to-subtract-2': 'It looks like you multiplied by the number of sides. Split the polygon into triangles: that makes n minus 2 of them.',
  'geo-angles.mc.used-n-minus-1': 'It looks like you used n minus 1 triangles. From one corner, a polygon splits into n minus 2 triangles.',
  'geo-angles.mc.gave-the-total-not-one-angle': 'That is the sum of all the angles. A regular polygon has equal angles, so divide by the number of angles.',
  'geo-angles.mc.used-360-over-n': 'That is an exterior angle of a regular polygon. The interior angle is 180 minus that.',
  'geo-angles.mc.used-the-triangle-total': 'It looks like you used 180, the total for a triangle. Use the total for this polygon.',
  'geo-angles.mc.forgot-to-subtract-the-known-angles': 'That is the total of all the angles. Subtract the angles you already know.',

  /* ---- Geometry: circles ---- */
  'circ.lv1': 'Circumference from the radius, as a multiple of pi.',
  'circ.lv2': 'Area from the radius, as a multiple of pi.',
  'circ.lv3': 'Area or circumference from the diameter.',
  'circ.lv4': 'Find the radius from the area or circumference.',
  'circ.lv5': 'Arc length and sector area.',
  'circ.p.circ': 'A circle has radius {r}. What is its circumference? Give the answer as a multiple of \\(\\pi\\): enter the number in front of \\(\\pi\\).',
  'circ.p.area': 'A circle has radius {r}. What is its area? Give the answer as a multiple of \\(\\pi\\): enter the number in front of \\(\\pi\\).',
  'circ.p.areaD': 'A circle has diameter {d}. What is its area? Give the answer as a multiple of \\(\\pi\\): enter the number in front of \\(\\pi\\).',
  'circ.p.circD': 'A circle has diameter {d}. What is its circumference? Give the answer as a multiple of \\(\\pi\\): enter the number in front of \\(\\pi\\).',
  'circ.p.findrA': 'A circle has area \\({k}\\pi\\). What is its radius?',
  'circ.p.findrC': 'A circle has circumference \\({k}\\pi\\). What is its radius?',
  'circ.p.arc': 'A sector of a circle has a central angle of {th} degrees and a radius of {r}. What is the length of its arc? Give the answer as a multiple of \\(\\pi\\): enter the number in front of \\(\\pi\\).',
  'circ.p.sector': 'A sector of a circle has a central angle of {th} degrees and a radius of {r}. What is the area of the sector? Give the answer as a multiple of \\(\\pi\\): enter the number in front of \\(\\pi\\).',
  'circ.h1.circ': 'Circumference is 2 times pi times the radius.',
  'circ.h2.circ': 'Put in the radius: \\(2 \\times {r}\\).',
  'circ.h1.area': 'Area is pi times the radius squared.',
  'circ.h2.area': 'Square the radius: \\({r}^2\\).',
  'circ.h1.areaD': 'The radius is half the diameter. Find it first, then use area = pi times radius squared.',
  'circ.h2.areaD': 'The radius is \\({d} \\div 2 = {r}\\).',
  'circ.h1.circD': 'Circumference is pi times the diameter.',
  'circ.h2.circD': 'The diameter is {d}, so the circumference is {d} times pi.',
  'circ.h1.findrA': 'Area is pi times the radius squared. Set that equal to the area you were given.',
  'circ.h2.findrA': 'You need a number whose square is {k}.',
  'circ.h1.findrC': 'Circumference is 2 times pi times the radius.',
  'circ.h2.findrC': 'Divide {k} by 2.',
  'circ.h1.arc': 'Arc length is a fraction of the circumference. The fraction is the angle over 360.',
  'circ.h2.arc': 'The fraction of the circle is \\(\\frac{{th}}{360}\\).',
  'circ.h1.sector': 'Sector area is a fraction of the whole area. The fraction is the angle over 360.',
  'circ.h2.sector': 'The fraction of the circle is \\(\\frac{{th}}{360}\\).',
  'circ.s.circ': 'Circumference \\(= 2\\pi r = 2\\pi({r}) = {k}\\pi\\).',
  'circ.s.area': 'Area \\(= \\pi r^2 = \\pi({r})^2 = {k}\\pi\\).',
  'circ.s.half': 'The radius is half the diameter: \\({d} \\div 2 = {r}\\).',
  'circ.s.circD': 'Circumference \\(= \\pi d = {d}\\pi\\).',
  'circ.s.findrA': '\\(\\pi r^2 = {k}\\pi\\), so \\(r^2 = {k}\\) and \\(r = {r}\\).',
  'circ.s.findrC': '\\(2\\pi r = {k}\\pi\\), so \\(r = {k} \\div 2 = {r}\\).',
  'circ.s.arc': 'Arc \\(= \\frac{{th}}{360} \\times 2\\pi({r}) = {k}\\pi\\).',
  'circ.s.sector': 'Area \\(= \\frac{{th}}{360} \\times \\pi({r})^2 = {k}\\pi\\).',
  'geo-circle.mc.used-the-area-formula': 'It looks like you squared the radius. That is for area. Circumference is 2 times pi times the radius.',
  'geo-circle.mc.forgot-the-2': 'It looks like the 2 is missing. Circumference is 2 times pi times the radius.',
  'geo-circle.mc.used-the-circumference-formula': 'It looks like you used the circumference formula. Area is pi times the radius squared.',
  'geo-circle.mc.used-the-diameter-as-the-radius': 'It looks like the diameter was used as the radius. The radius is half the diameter.',
  'geo-circle.mc.halved-instead-of-squaring': 'You found the radius, but area needs the radius squared.',
  'geo-circle.mc.doubled-the-diameter': 'It looks like the diameter was doubled. Circumference is pi times the diameter: the number in front of pi is just the diameter.',
  'geo-circle.mc.halved-the-diameter': 'That is the radius. Circumference is pi times the diameter.',
  'geo-circle.mc.halved-the-area-number': 'It looks like you halved the area number. Area is pi times the radius squared, so the radius is the square root.',
  'geo-circle.mc.gave-the-area-number': 'That is the radius squared. Take the square root to get the radius.',
  'geo-circle.mc.forgot-to-halve': 'That is the diameter. The radius is half of it.',
  'geo-circle.mc.doubled-instead-of-halving': 'It looks like you doubled. Circumference is 2 pi r, so r is the circumference number divided by 2.',
  'geo-circle.mc.used-the-whole-circumference': 'That is the circumference of the whole circle. The arc is only part of it: the angle over 360.',
  'geo-circle.mc.used-the-sector-area-formula': 'It looks like you used the area of the sector. Arc length is a fraction of the circumference.',
  'geo-circle.mc.used-the-whole-area': 'That is the area of the whole circle. The sector is only part of it: the angle over 360.',
  'geo-circle.mc.used-the-arc-length-formula': 'It looks like you used the arc length. Sector area is a fraction of the area, pi times the radius squared.',

  /* ---- Geometry: coordinates ---- */
  'coord.lv1': 'Distance along a horizontal or vertical line.',
  'coord.lv2': 'Midpoint when the sums are even.',
  'coord.lv3': 'Distance between any two points, with whole-number answers.',
  'coord.lv4': 'Midpoint with half-number answers.',
  'coord.lv5': 'Find an endpoint from the midpoint and the other endpoint.',
  'coord.p.dist': 'How far apart are the points \\({A}\\) and \\({B}\\)?',
  'coord.p.mid': 'Find the midpoint of the segment from \\({A}\\) to \\({B}\\). Give the answer as a pair.',
  'coord.p.end': 'The midpoint of segment AB is \\({M}\\) and A is \\({A}\\). Find the coordinates of B. Give the answer as a pair.',
  'coord.h1.line': 'Look at which coordinate the two points share.',
  'coord.h2.line': 'Subtract the coordinates that are different, and ignore the sign.',
  'coord.h1.dist': 'Find how far apart the x values are and how far apart the y values are. Those are the legs of a right triangle.',
  'coord.h2.dist': 'The legs are {dx} and {dy}. Use the Pythagorean theorem.',
  'coord.h1.mid': 'The midpoint is the average of the x values and the average of the y values.',
  'coord.h2.mid': 'For x: add {x1} and {x2}, then divide by 2.',
  'coord.h1.end': 'The midpoint is halfway, so B is as far past the midpoint as A is before it.',
  'coord.h2.end': 'For x: the midpoint is {mx}, so B has x equal to \\(2 \\times {mx} - {x1}\\).',
  'coord.s.line': 'The points share one coordinate, so they are on a horizontal or vertical line. The distance is the difference in the other coordinate: {len}.',
  'coord.s.diff': 'Horizontal difference: {dx}. Vertical difference: {dy}.',
  'coord.s.sqrt': 'Distance \\(= \\sqrt{{dx}^2 + {dy}^2} = \\sqrt{{s}} = {c}\\).',
  'coord.s.midx': 'x: \\(({x1} + {x2}) \\div 2 = {s} \\div 2 = {mx}\\).',
  'coord.s.midy': 'y: \\(({y1} + {y2}) \\div 2 = {s} \\div 2 = {my}\\).',
  'coord.s.endx': 'x: \\(2 \\times {mx} - {x1} = {x2}\\).',
  'coord.s.endy': 'y: \\(2 \\times {my} - {y1} = {y2}\\).',
  'geo-coordinates.mc.added-the-coordinates': 'It looks like the coordinates were added. Distance comes from the differences between them.',
  'geo-coordinates.mc.counted-one-too-few': 'It looks like you counted the squares, not the steps. Subtract the coordinates instead.',
  'geo-coordinates.mc.forgot-the-square-root': 'You found the squared distance. Take the square root to get the distance.',
  'geo-coordinates.mc.added-the-differences': 'It looks like the two differences were added. The distance is the long side of a right triangle: use the Pythagorean theorem.',
  'geo-coordinates.mc.added-without-halving': 'It looks like you added the coordinates and stopped. The midpoint is the average, so divide by 2.',
  'geo-coordinates.mc.subtracted-instead-of-adding': 'It looks like you subtracted. The midpoint averages the coordinates: add them, then halve.',
  'geo-coordinates.mc.mixed-up-x-and-y': 'You have the right numbers in the wrong order. A point is written (x, y).',
  'geo-coordinates.mc.forgot-to-double': 'It looks like the midpoint was not doubled. B is twice as far from A as the midpoint is, so use 2 times the midpoint minus A.',
  'geo-coordinates.mc.gave-the-midpoint-back': 'That is the midpoint. B is the other end, further along.',
  'geo-coordinates.mc.added-the-points': 'It looks like the two points were added. Use 2 times the midpoint minus A.',

  /* ---- Geometry: solids ---- */
  'solid.lv1': 'Volume of a rectangular box.',
  'solid.lv2': 'Surface area of a rectangular box.',
  'solid.lv3': 'Volume of a triangular prism.',
  'solid.lv4': 'Volume of a square pyramid, or a cylinder as a multiple of pi.',
  'solid.lv5': 'Volume of a cone, or the surface area of a cylinder, as a multiple of pi.',
  'solid.p.box': 'A box is {l} cm long, {w} cm wide and {h} cm tall. What is its volume, in cubic centimeters?',
  'solid.p.sa': 'A box is {l} cm long, {w} cm wide and {h} cm tall. What is its surface area, in square centimeters?',
  'solid.p.tri': 'A triangular prism has a triangular base with base {b} cm and height {h} cm. The prism is {L} cm long. What is its volume, in cubic centimeters?',
  'solid.p.pyr': 'A square pyramid has a base side of {s} cm and a height of {h} cm. What is its volume, in cubic centimeters?',
  'solid.p.cyl': 'A cylinder has radius {r} cm and height {h} cm. What is its volume? Give the answer as a multiple of \\(\\pi\\): enter the number in front of \\(\\pi\\).',
  'solid.p.cone': 'A cone has radius {r} cm and height {h} cm. What is its volume? Give the answer as a multiple of \\(\\pi\\): enter the number in front of \\(\\pi\\).',
  'solid.p.cylsa': 'A cylinder has radius {r} cm and height {h} cm. What is its total surface area, including both circles? Give the answer as a multiple of \\(\\pi\\): enter the number in front of \\(\\pi\\).',
  'solid.h1.box': 'Volume is length times width times height.',
  'solid.h2.box': 'First find the base area: \\({l} \\times {w}\\).',
  'solid.h1.sa': 'A box has six faces in three matching pairs. Find the area of each kind of face.',
  'solid.h2.sa': 'The three different faces have areas \\({l} \\times {w}\\), \\({l} \\times {h}\\) and \\({w} \\times {h}\\).',
  'solid.h1.tri': 'Volume is the area of the base times the length. The base is a triangle, so its area is half base times height.',
  'solid.h2.tri': 'Base area: \\(\\frac{1}{2} \\times {b} \\times {h}\\).',
  'solid.h1.pyr': 'A pyramid holds one third of the prism with the same base and height.',
  'solid.h2.pyr': 'The base area is \\({s} \\times {s}\\).',
  'solid.h1.cyl': 'Volume is the area of the circle times the height. The circle has area pi times the radius squared.',
  'solid.h2.cyl': 'The circle has area \\(\\pi \\times {r}^2\\).',
  'solid.h1.cone': 'A cone holds one third of the cylinder with the same base and height.',
  'solid.h2.cone': 'The cylinder would hold \\(\\pi \\times {r}^2 \\times h\\). Take one third of that.',
  'solid.h1.cylsa': 'The surface is two circles plus the curved side. Unroll the side into a rectangle.',
  'solid.h2.cylsa': 'The side is a rectangle \\(2\\pi \\times {r}\\) wide and as tall as the cylinder.',
  'solid.s.box': 'Volume \\(= {l} \\times {w} \\times {h} = {v}\\).',
  'solid.s.sa1': 'Face areas: \\({l} \\times {w} = {a}\\), \\({l} \\times {h} = {b}\\), \\({w} \\times {h} = {c}\\). Together: \\({s}\\).',
  'solid.s.sa2': 'Each kind of face appears twice: \\(2 \\times {s} = {sa}\\).',
  'solid.s.tri1': 'Triangle area: \\(\\frac{1}{2} \\times {b} \\times {h} = {a}\\).',
  'solid.s.tri2': 'Volume: \\({a} \\times {L} = {v}\\).',
  'solid.s.pyr1': 'Base area: \\({s}^2 = {b}\\).',
  'solid.s.pyr2': 'Volume \\(= \\frac{1}{3} \\times {b} \\times {h} = {v}\\).',
  'solid.s.cyl': 'Volume \\(= \\pi r^2 h = \\pi \\times {r}^2 \\times {h} = {k}\\pi\\).',
  'solid.s.cone': 'Volume \\(= \\frac{1}{3}\\pi r^2 h = \\frac{1}{3}\\pi \\times {r}^2 \\times {h} = {k}\\pi\\).',
  'solid.s.cylsa': 'Two circles: \\(2\\pi({r})^2 = {ends}\\pi\\). Curved side: \\(2\\pi({r}) \\times {h} = {side}\\pi\\). Total: \\({k}\\pi\\).',
  'geo-solids.mc.added-the-edges': 'It looks like the edges were added. Volume multiplies length, width and height.',
  'geo-solids.mc.found-one-face': 'That is the area of one face. Volume needs the height too.',
  'geo-solids.mc.found-the-volume': 'It looks like you found the volume. Surface area adds up the areas of the faces.',
  'geo-solids.mc.forgot-to-double': 'It looks like each face was counted once. A box has two of each kind of face.',
  'geo-solids.mc.forgot-the-half': 'The triangle at the end has half the area of a rectangle: half base times height.',
  'geo-solids.mc.used-the-base-edge-as-the-whole-base': 'It looks like the base was treated as a rectangle. The base is a triangle, so its area is half base times height.',
  'geo-solids.mc.forgot-the-third': 'It looks like the one third is missing. A cone or pyramid holds one third of the matching cylinder or prism.',
  'geo-solids.mc.used-the-prism-formula-with-half': 'A pyramid holds one third, not one half, of the matching prism.',
  'geo-solids.mc.forgot-to-square-the-radius': 'It looks like the radius was not squared. The circle at the base has area pi times the radius squared.',
  'geo-solids.mc.used-the-diameter': 'It looks like the diameter was used as the radius. Use the radius, then square it.',
  'geo-solids.mc.left-out-the-circles': 'It looks like only the curved side was counted. The two circles on the ends are part of the surface.',

  /* ---- Geometry: trigonometry ---- */
  'trig.lv1': 'Sine from the side lengths.',
  'trig.lv2': 'Cosine from the side lengths.',
  'trig.lv3': 'Tangent from the side lengths.',
  'trig.lv4': 'Sine, cosine or tangent of either acute angle, with larger triangles.',
  'trig.lv5': 'Use a ratio to find a missing side.',
  'trig.name.sin': '\\sin',
  'trig.name.cos': '\\cos',
  'trig.name.tan': '\\tan',
  'trig.w.hypotenuse': 'hypotenuse',
  'trig.w.adjacent': 'adjacent side',
  'trig.w.opposite': 'opposite side',
  'trig.p.ratio': 'In right triangle ABC, the right angle is at C. AC = {AC}, BC = {BC} and AB = {AB}. What is \\({which} {angle}\\)? Give the answer as a fraction in simplest form.',
  'trig.p.solve': 'In a right triangle, \\({tex}\\). The {known} is {given}. How long is the {want}?',
  'trig.h1.sin': 'Sine is opposite over hypotenuse. The hypotenuse is the longest side, across from the right angle.',
  'trig.h1.cos': 'Cosine is adjacent over hypotenuse. The hypotenuse is the longest side, across from the right angle.',
  'trig.h1.tan': 'Tangent is opposite over adjacent. The hypotenuse is not used.',
  'trig.h2': 'The side opposite angle {angle} is the one that does not touch it. The adjacent side touches it and is not the hypotenuse.',
  'trig.h1.solve': 'The ratio compares two sides. Use it to scale the side you know.',
  'trig.h2.solve': 'The two sides are in the ratio {num} to {den}.',
  'trig.s.label': 'For angle {angle}: the opposite side is {opp}, the adjacent side is {adj} and the hypotenuse is {hyp}.',
  'trig.s.ratio': '\\({which} {angle} = \\frac{{n}}{{d}} = {ans}\\).',
  'trig.s.solve1': 'The ratio \\({tex}\\) compares two sides. The {known} is {given}.',
  'trig.s.solve2': 'The sides scale by \\({given} \\div {den} = {k}\\), so the other side is \\({num} \\times {k} = {ans}\\).',
  'geo-trig.mc.used-the-ratio-upside-down': 'It looks like the ratio was turned upside down. Divide the side you know by its part of the ratio, then multiply by the other part.',
  'geo-trig.mc.gave-the-given-side': 'That is the side you were told. Use the ratio to find the other side.',
  'geo-trig.mc.used-a-different-ratio': 'That is a different ratio. Check which one you need: sine is opposite over hypotenuse, cosine is adjacent over hypotenuse, tangent is opposite over adjacent.',
  'geo-trig.mc.flipped-the-ratio': 'It looks like the fraction is upside down. Check which side goes on top.',
  'geo-trig.mc.mixed-up-opposite-and-adjacent': 'It looks like opposite and adjacent were swapped. The opposite side is across from the angle. The adjacent side touches it.',

  /* ---- Geometry: similar figures ---- */
  'sim.lv1': 'A missing side when the scale factor is a whole number.',
  'sim.lv2': 'A missing side when the scale factor is a fraction bigger than 1.',
  'sim.lv3': 'A missing side when the figure shrinks.',
  'sim.lv4': 'Find the scale factor.',
  'sim.lv5': 'Find an area from a length ratio.',
  'sim.w.large': 'larger',
  'sim.w.small': 'smaller',
  'sim.p.side': 'Two triangles are similar. In the {first} triangle two sides are {s1} and {s2}. In the {second} triangle the side matching {s1} is {S1}. How long is the side matching {s2}?',
  'sim.p.scale': 'Two triangles are similar. A side of length {s1} in the first triangle matches a side of length {S1} in the second. What is the scale factor from the first triangle to the second?',
  'sim.p.area': 'Two similar figures have lengths in the ratio {p} to {q}. The smaller figure has an area of {A} square units. What is the area of the larger figure, in square units?',
  'sim.h1.side': 'Similar shapes scale every side by the same factor. Find the factor from the pair of matching sides you know.',
  'sim.h2.side': 'The factor is \\({S1} \\div {s1}\\).',
  'sim.h1.scale': 'The scale factor is the new length divided by the old length.',
  'sim.h2.scale': 'Divide \\({S1} \\div {s1}\\).',
  'sim.h1.area': 'When lengths scale by a factor, areas scale by that factor squared.',
  'sim.h2.area': 'The lengths are in the ratio {p} to {q}, so the areas are in the ratio \\({p}^2\\) to \\({q}^2\\).',
  'sim.s.k': 'Scale factor: \\({S1} \\div {s1} = {k}\\).',
  'sim.s.apply': 'Multiply the other side by it: \\({s2} \\times {k} = {v}\\).',
  'sim.s.scale': 'Scale factor \\(= \\frac{{S1}}{{s1}} = {k}\\).',
  'sim.s.area1': 'The area ratio is the length ratio squared: \\({p}^2 : {q}^2 = {p2} : {q2}\\).',
  'sim.s.area2': 'Larger area \\(= {A} \\times \\frac{{q2}}{{p2}} = {v}\\).',
  'geo-similar.mc.added-the-same-amount': 'It looks like the same amount was added to each side. Similar shapes scale by multiplying, not adding.',
  'geo-similar.mc.used-the-scale-factor-upside-down': 'It looks like the scale factor is upside down. Compare new over old, then multiply the old side by it.',
  'geo-similar.mc.flipped-the-scale-factor': 'It looks like the fraction is upside down. The scale factor is new length over old length.',
  'geo-similar.mc.subtracted-the-sides': 'It looks like the sides were subtracted. The scale factor is a ratio, so divide.',
  'geo-similar.mc.forgot-to-square': 'It looks like the ratio was not squared. Areas scale by the square of the length ratio.',
  'geo-similar.mc.squared-the-wrong-way-round': 'It looks like the area ratio is upside down. The larger figure has the larger area.'
};
