/* =====================================================================
   PRACTICE (strings): every sentence a student sees from the practice generators, keyed, with {slots}.
   Nothing is written into the logic, so a translation is a copy of this table. TeX is in String.raw-style
   double-backslash form inside normal strings. Do not put a literal {word} in TeX: {word} is a slot.
   ===================================================================== */
Practice.T = {
  /* ---- answer formats (shown under the answer box) ---- */
  'ans.whole': 'Enter a whole number.',
  'ans.number': 'Enter a number. You can write a whole number, a decimal, or a fraction like 3/4.',
  'ans.fraction': 'Enter a fraction in simplest form, like 5/6. A mixed number like 1 1/6 or a decimal that ends is fine too.',
  'ans.length': 'Enter a number. You may add the unit if you like.',
  'ans.pair': 'Enter the pair as (x, y), for example (2, -1).',
  'word.add': 'Add',
  'word.subtract': 'Subtract',
  'form.simplify': 'That value is right, but the fraction is not in simplest form. Divide the top and bottom by the same number, then enter it again.',

  /* ---- G4: multiplying multi-digit numbers ---- */
  'mult.lv1': 'A two-digit number times a one-digit number, small.',
  'mult.lv2': 'A two-digit number times a one-digit number, up to 99 by 9.',
  'mult.lv3': 'A three-digit number times a one-digit number.',
  'mult.lv4': 'Two two-digit numbers, small.',
  'mult.lv5': 'Two two-digit numbers, up to 99 by 99.',
  'mult.lv6': 'A three-digit number times a two-digit number.',
  'mult.p.eq': 'Find \\({a} \\times {b}\\).',
  'mult.p.chairs': 'A hall has {a} rows of chairs with {b} chairs in each row. How many chairs are there in all?',
  'mult.p.boxes': 'One box holds {b} pencils. How many pencils are in {a} boxes?',
  'mult.h1': 'Draw an area model. Break each number into hundreds, tens and ones, and multiply the pieces.',
  'mult.h2': 'Start with the first piece. {first}',
  'mult.h3': 'Here are all the pieces of the area model: {list}. Now add them.',
  'mult.s1': 'Break each number into place-value pieces: \\({a} = {pa}\\) and \\({b} = {pb}\\).',
  'mult.s1b': 'Break {a} into place-value pieces: \\({a} = {pa}\\). The other number, {b}, stays whole.',
  'mult.s2': 'Multiply each piece by each piece: {list}.',
  'mult.s3': 'Add the pieces: \\({sum}\\).',
  'g4-multiply.mc.missing-middle-pieces': 'It looks like you multiplied tens by tens and ones by ones only. An area model has four pieces. Do not forget tens times ones, and ones times tens.',
  'g4-multiply.mc.digits-without-place-value': 'It looks like you multiplied the digits as if each one meant just itself. A 4 in the tens place means 40. Multiply the whole pieces, like 40 times 5.',
  'g4-multiply.mc.left-out-the-ones-piece': 'It looks like one piece is missing. The ones digit also has to be multiplied, then added to the rest.',

  /* ---- G5: adding and subtracting fractions ---- */
  'frac.lv1': 'Add two fractions when one denominator is a multiple of the other. The sum is less than 1.',
  'frac.lv2': 'Add two fractions with different denominators that share no factor. The sum is less than 1.',
  'frac.lv3': 'Add two fractions with unlike denominators. The sum can be more than 1.',
  'frac.lv4': 'Subtract fractions with unlike denominators.',
  'frac.lv5': 'Add or subtract with larger denominators that share a factor, like 6 and 4.',
  'frac.p.add': 'Add. \\({T1} + {T2}\\)',
  'frac.p.sub': 'Subtract. \\({T1} - {T2}\\)',
  'frac.p.pizza': 'Mia ate \\({T1}\\) of a pizza at lunch and \\({T2}\\) of the same pizza at dinner. How much of the pizza did she eat in all?',
  'frac.p.cups': 'A recipe uses \\({T1}\\) cup of milk and \\({T2}\\) cup of juice. How many cups of liquid is that in all?',
  'frac.p.ribbon': 'Jo has \\({T1}\\) of a yard of ribbon and cuts off \\({T2}\\) of a yard. How much ribbon is left, in yards?',
  'frac.h1': 'You can only add or subtract pieces of the same size. Find a common denominator first.',
  'frac.h2': 'The smallest number that both {d1} and {d2} go into is {L}. Use {L} as the denominator.',
  'frac.h3': 'Rewrite \\({T1}\\) as \\({s1}\\) and \\({T2}\\) as \\({s2}\\). Then work with the tops.',
  'frac.s1': 'Find a common denominator. The smallest number that both {d1} and {d2} go into is {L}.',
  'frac.s2': 'Rewrite both fractions with denominator {L}: \\({T1} = {s1}\\) and \\({T2} = {s2}\\).',
  'frac.s3add': 'Add the tops and keep the bottom: \\({a} + {b} = {r}\\).',
  'frac.s3sub': 'Subtract the tops and keep the bottom: \\({a} - {b} = {r}\\).',
  'frac.s4': 'Simplify: \\({r} = {ans}\\).',
  'g5-fraction-sum.mc.added-tops-and-bottoms': 'It looks like you added the tops and added the bottoms. Pieces of different sizes cannot be counted together. Rename both fractions with a common denominator first, then add only the tops.',
  'g5-fraction-sum.mc.subtracted-tops-and-bottoms': 'It looks like you subtracted the tops and subtracted the bottoms. The bottom tells the size of the pieces, and it stays the same. Rename both fractions with a common denominator first.',
  'g5-fraction-sum.mc.forgot-to-rename-the-tops': 'You found the common denominator, but the tops have to change too. When you cut each piece into smaller pieces, you get more pieces. Multiply the top by the same number as the bottom.',

  /* ---- G8: linear equations ---- */
  'lin.lv1': 'One step: add or subtract a number. Example: x + 4 = 9.',
  'lin.lv2': 'One step: multiply to undo a division, or divide. Example: 3x = 21.',
  'lin.lv3': 'Two steps. Example: 2x + 3 = 11.',
  'lin.lv4': 'Variables on both sides. Example: 5x + 2 = 2x + 14.',
  'lin.lv5': 'Brackets that need distributing. Example: 3(x + 2) = 18.',
  'lin.lv6': 'Brackets and variables on both sides, with negatives.',
  'lin.p.solve': 'Solve for \\(x\\). \\({eq}\\)',
  'lin.w.add': 'I think of a number and add {b}. The result is {d}. What is the number?',
  'lin.w.sub': 'I think of a number and subtract {b}. The result is {d}. What is the number?',
  'lin.w.mul': 'I think of a number and multiply it by {a}. The result is {d}. What is the number?',
  'lin.w.muladd': 'I think of a number, multiply it by {a}, then add {b}. The result is {d}. What is the number?',
  'lin.w.mulsub': 'I think of a number, multiply it by {a}, then subtract {b}. The result is {d}. What is the number?',
  'lin.h1.one': 'Get x alone. Do the opposite of what was done to x.',
  'lin.h1.paren': 'First get rid of the brackets by distributing. Then get x alone.',
  'lin.h1.both': 'Collect the x terms on one side and the plain numbers on the other, then divide.',
  'lin.h2.distribute': 'Distribute {a}: multiply it by every term inside the brackets.',
  'lin.h2.move': '{op} {t} on both sides.',
  'lin.h2.divide': 'Divide both sides by {A}.',
  'lin.s.distribute': 'Distribute {a} to both terms inside the brackets: \\({eq}\\).',
  'lin.s.xterm': '{op} \\({t}\\) on both sides to collect the x terms: \\({eq}\\).',
  'lin.s.const': '{op} {t} on both sides to get the x term alone: \\({eq}\\).',
  'lin.s.divide': 'Divide both sides by {A}: \\(x = {ans}\\).',
  'lin.s.done': 'So \\(x = {ans}\\).',
  'g8-linear-equation.mc.moved-the-number-with-the-wrong-sign': 'It looks like you added when you should have subtracted (or the other way round). To undo +b, subtract b from both sides. To undo -b, add b.',
  'g8-linear-equation.mc.multiplied-only-the-first-term': 'It looks like you multiplied only the first term inside the brackets. The number outside multiplies every term inside.',
  'g8-linear-equation.mc.moved-the-x-term-with-the-wrong-sign': 'It looks like the x terms were combined with the wrong sign. To move a term to the other side, do the opposite: subtract if it was added, add if it was subtracted.',
  'g8-linear-equation.mc.divided-only-one-term': 'It looks like you divided only one term by the number in front of x. Subtract the plain number first, then divide the whole right side.',
  'g8-linear-equation.mc.forgot-to-divide': 'It looks like the last step is missing. After you move the plain number, divide both sides by the number in front of x.',
  'g8-linear-equation.mc.subtracted-instead-of-dividing': 'It looks like you subtracted. The number in front of x multiplies it, so the opposite is to divide.',

  /* ---- G8: Pythagorean theorem ---- */
  'pyth.lv1': 'Find the hypotenuse of a small right triangle, like 3 and 4.',
  'pyth.lv2': 'Find the hypotenuse when the sides are multiples, like 6 and 8.',
  'pyth.lv3': 'Find a missing leg.',
  'pyth.lv4': 'Find any missing side in larger triangles.',
  'pyth.lv5': 'Real situations: ladders, screens and wires.',
  'pyth.p.hyp': 'A right triangle has legs of length {a} and {b}. How long is the hypotenuse?',
  'pyth.p.leg': 'A right triangle has a hypotenuse of length {c} and one leg of length {a}. How long is the other leg?',
  'pyth.p.ladder': 'A {c} foot ladder leans against a wall. The foot of the ladder is {a} feet from the wall. How high up the wall does the ladder reach, in feet?',
  'pyth.p.tv': 'A TV screen is {a} inches wide and {b} inches tall. How long is its diagonal, in inches?',
  'pyth.p.wire': 'A pole is {a} metres tall. A wire runs from its top to a point on the ground {b} metres from the base of the pole. How long is the wire, in metres?',
  'pyth.h1.hyp': 'The hypotenuse is the side across from the right angle. Use a squared plus b squared equals c squared.',
  'pyth.h1.leg': 'The hypotenuse is the longest side, across from the right angle. Put it in as c, then solve for the missing leg.',
  'pyth.s.theorem': 'In a right triangle, \\(a^2 + b^2 = c^2\\), where c is the hypotenuse.',
  'pyth.s.hyp1': 'Put in the legs: \\({a}^2 + {b}^2 = c^2\\).',
  'pyth.s.hyp2': 'Square them: \\({a2} + {b2} = {sum}\\), so \\(c^2 = {sum}\\).',
  'pyth.s.hyp3': 'Take the square root: \\(c = \\sqrt{{sum}} = {ans}\\).',
  'pyth.s.leg1': 'Put in the known leg and the hypotenuse: \\({k}^2 + u^2 = {c}^2\\), where u is the missing leg.',
  'pyth.s.leg2': 'Square them: \\({k2} + u^2 = {c2}\\).',
  'pyth.s.leg3': 'Subtract {k2} from both sides: \\(u^2 = {c2} - {k2} = {diff}\\).',
  'pyth.s.leg4': 'Take the square root: \\(u = \\sqrt{{diff}} = {ans}\\).',
  'g8-pythagorean-side.mc.added-the-legs': 'It looks like you added the two leg lengths. The hypotenuse is not the sum of the legs. Square each leg, add the squares, then take the square root.',
  'g8-pythagorean-side.mc.forgot-the-square-root': 'You found the square of the side. The last step is to take the square root to get the length.',
  'g8-pythagorean-side.mc.subtracted-the-lengths': 'It looks like you subtracted the lengths. Subtract the squares instead, then take the square root.',

  /* ---- A1: systems of two linear equations ---- */
  'sys.lv1': 'One equation is already solved for y. Substitute.',
  'sys.lv2': 'Both equations in standard form. The y terms are opposites, so adding removes y.',
  'sys.lv3': 'Multiply one equation first, then add or subtract.',
  'sys.lv4': 'Multiply both equations before you eliminate.',
  'sys.lv5': 'Negative coefficients and negative solutions.',
  'sys.p.solve': 'Solve the system. Give the answer as a pair \\((x, y)\\).<div class="pr-eq">\\({e1}\\)</div><div class="pr-eq">\\({e2}\\)</div>',
  'sys.h1.sub': 'One equation says what y equals. Put that expression in place of y in the other equation.',
  'sys.h1.elim': 'Make the y terms match, or be opposites, by multiplying. Then add or subtract the equations to remove y.',
  'sys.s.sub1': 'The first equation says \\({rhs}\\). Put that in place of y in the second equation: \\({eq}\\).',
  'sys.s.sub2': 'Combine like terms: \\({eq}\\).',
  'sys.s.sub3': 'Solve for x: \\({eq}\\), so \\(x = {x}\\).',
  'sys.s.sub4': 'Find y from the first equation: \\({calc}\\).',
  'sys.s.done': 'The solution is \\(({x}, {y})\\).',
  'sys.s.pick': 'Remove y. The y numbers are {b1} and {b2}. The smallest size that both fit into is {L}.',
  'sys.s.keep': 'The y terms already match in size: \\({e1}\\) and \\({e2}\\).',
  'sys.s.scale': 'Multiply equation 1 by {m1} and equation 2 by {m2} so the y terms match in size: \\({e1}\\) and \\({e2}\\).',
  'sys.s.add': 'The y terms are opposites. Add the equations: \\({eq}\\), so \\(x = {x}\\).',
  'sys.s.subtract': 'The y terms are the same. Subtract the equations: \\({eq}\\), so \\(x = {x}\\).',
  'sys.s.back': 'Put \\(x = {x}\\) into equation 1. That leaves \\({eq}\\), so \\(y = {y}\\).',
  'a1-system-solve.mc.swapped-the-order': 'You have the right two numbers, but in the wrong order. A pair is written (x, y): x first.',
  'a1-system-solve.mc.sign-slip-on-y': 'Your x is right, but check the sign of y when you put x back in.',
  'a1-system-solve.mc.sign-slip-on-x': 'Your y is right, but check the sign of x. Look at the step where x came from.',
  /* ---- more answer formats ---- */
  'ans.decimal': 'Enter a decimal, like 2.87. A fraction is fine too.',
  'ans.integer': 'Enter a whole number. Use a minus sign for a negative number, like -4.',
  'ans.percent': 'Enter the percent as a number, like 25. The % sign is optional.',

  /* ---- G4: division ---- */
  'div.lv1': 'A two-digit number divided by 2 to 5. No remainder.',
  'div.lv2': 'A three-digit number divided by 2 to 5. No remainder.',
  'div.lv3': 'A three-digit number divided by 6 to 9. No remainder.',
  'div.lv4': 'A four-digit number divided by a one-digit number. No remainder.',
  'div.lv5': 'Quotients with a zero inside, like 4 0 5.',
  'div.p.eq': 'Find \\({a} \\div {d}\\).',
  'div.p.stickers': 'There are {a} stickers. They are shared equally among {d} children. How many stickers does each child get?',
  'div.p.boxes': 'A box holds {d} crayons. How many boxes are needed to hold {a} crayons?',
  'div.h1': 'Ask: how many groups of {d} fit? Break the answer into place-value pieces: hundreds, tens and ones.',
  'div.h2': 'Try {p} groups first. \\({d} \\times {p} = {prod}\\). That leaves {left} still to divide.',
  'div.h3': 'The answer is the sum of these pieces: {list}.',
  'div.s1': 'Find pieces of the answer. For each piece, multiply by {d}: {list}.',
  'div.s2': 'Check that the products add up to the number you started with: \\({sum} = {a}\\).',
  'div.s3': 'So \\({a} \\div {d} = {sum} = {q}\\).',
  'g4-divide.mc.multiplied-instead-of-dividing': 'It looks like you multiplied. Dividing is splitting into equal groups, so the answer is smaller than the number you start with.',
  'g4-divide.mc.subtracted-instead-of-dividing': 'It looks like you subtracted. Ask instead how many groups of the divisor fit into the number.',
  'g4-divide.mc.answer-ten-times-too-big': 'Your digits are right, but the answer is ten times too big. Estimate first: about how many groups should you get? Then check each place.',
  'g4-divide.mc.dropped-the-zero': 'It looks like a zero was left out. A zero in the answer holds a place. Without it the digits slide into the wrong places.',

  /* ---- G4: rectangles ---- */
  'rect.lv1': 'Find the area of a small rectangle.',
  'rect.lv2': 'Find the perimeter of a small rectangle.',
  'rect.lv3': 'Area or perimeter of a larger rectangle.',
  'rect.lv4': 'Find a missing side from the area.',
  'rect.lv5': 'Find a missing side from the perimeter.',
  'rect.p.area': 'A rectangle is {l} {u} long and {w} {u} wide. What is its area, in square {u}?',
  'rect.p.perim': 'A rectangle is {l} {u} long and {w} {u} wide. What is its perimeter, in {u}?',
  'rect.p.missA': 'A rectangle has an area of {A} square {u} and is {w} {u} wide. How long is it, in {u}?',
  'rect.p.missP': 'A rectangle has a perimeter of {P} {u} and is {l} {u} long. How wide is it, in {u}?',
  'rect.c.area.q': 'Area = ?',
  'rect.c.perim.q': 'Perimeter = ?',
  'rect.c.area': 'Area = {A}',
  'rect.c.perim': 'Perimeter = {P}',
  'rect.h1.area': 'Area counts the squares inside. Multiply the length by the width.',
  'rect.h2.area': 'Multiply \\({l} \\times {w}\\).',
  'rect.h1.perim': 'Perimeter is the distance around. Add up all four sides.',
  'rect.h2.perim': 'A rectangle has two sides of {l} and two sides of {w}.',
  'rect.h1.missA': 'Area is length times width. Work backward: divide the area by the side you know.',
  'rect.h2.missA': 'Divide \\({A} \\div {w}\\).',
  'rect.h1.missP': 'The perimeter is two lengths plus two widths. Take away the two lengths you know, then split what is left between the two widths.',
  'rect.h2.missP': 'Two lengths make 2 \\(\\times\\) {l}. Subtract that from {P}.',
  'rect.s.area': 'Area = length \\(\\times\\) width, so \\({l} \\times {w} = {A}\\).',
  'rect.s.perim1': 'Add one length and one width: \\({l} + {w} = {s}\\).',
  'rect.s.perim2': 'A rectangle has two of each, so double it: \\(2 \\times {s} = {P}\\).',
  'rect.s.missA1': 'Area = length \\(\\times\\) width, so length = area \\(\\div\\) width.',
  'rect.s.missA2': '\\({A} \\div {w} = {l}\\).',
  'rect.s.missP1': 'The two lengths use up \\(2 \\times {l}\\). What is left for the two widths is \\({P} - 2 \\times {l} = {rest}\\).',
  'rect.s.missP2': 'Split it between two widths: \\({rest} \\div 2 = {w}\\).',
  'g4-rectangle.mc.added-instead-of-multiplying': 'It looks like you added the length and the width. Area counts squares inside, so multiply.',
  'g4-rectangle.mc.found-the-perimeter': 'It looks like you found the perimeter, the distance around. Area is the space inside: length times width.',
  'g4-rectangle.mc.added-just-two-sides': 'It looks like you added only two sides. A rectangle has four sides: two lengths and two widths.',
  'g4-rectangle.mc.found-the-area': 'It looks like you found the area. Perimeter is the distance around, so add the sides.',
  'g4-rectangle.mc.multiplied-instead-of-dividing': 'It looks like you multiplied. To find a missing side from the area, divide the area by the side you know.',
  'g4-rectangle.mc.subtracted-instead-of-dividing': 'It looks like you subtracted. Area is length times width, so the opposite is to divide.',
  'g4-rectangle.mc.forgot-to-halve': 'You found what is left for the two widths, but there are two of them. Split it in half.',
  'g4-rectangle.mc.took-away-only-one-length': 'It looks like you took away only one length. A rectangle has two lengths, so take away both.',

  /* ---- G5: decimals ---- */
  'dec.lv1': 'Add tenths, like 0.3 + 0.4.',
  'dec.lv2': 'Add hundredths, like 0.25 + 0.36.',
  'dec.lv3': 'Add decimals with different numbers of places, like 2.5 + 0.37.',
  'dec.lv4': 'Subtract decimals, including from a whole number.',
  'dec.lv5': 'Add or subtract up to thousandths.',
  'dec.unit1': 'tenths',
  'dec.unit2': 'hundredths',
  'dec.unit3': 'thousandths',
  'dec.p.add': 'Add. \\({a} + {b}\\)',
  'dec.p.sub': 'Subtract. \\({a} - {b}\\)',
  'dec.p.run': 'Sam ran {a} miles on Monday and {b} miles on Tuesday. How many miles did he run in all?',
  'dec.p.board': 'A board is {a} meters long. A piece {b} meters long is cut off. How long is the rest, in meters?',
  'dec.h1': 'Line up the decimal points, so tenths sit under tenths and hundredths under hundredths. Add zeros to fill in the empty places.',
  'dec.h2': 'Give both numbers the same number of decimal places: \\({A}\\) and \\({B}\\).',
  'dec.s1': 'Give both numbers the same number of decimal places: \\({A}\\) and \\({B}\\). The places now line up.',
  'dec.s2add': 'Think of them as {unit}. Add: \\({sa} + {sb} = {top}\\) {unit}.',
  'dec.s2sub': 'Think of them as {unit}. Subtract: \\({sa} - {sb} = {top}\\) {unit}.',
  'dec.s3': '{top} {unit} is written \\({ans}\\).',
  'g5-decimals.mc.added-as-whole-numbers': 'It looks like you added the digits as if the decimal points were not there. Line up the places first: tenths with tenths, hundredths with hundredths.',
  'g5-decimals.mc.misplaced-the-decimal-point': 'Your digits are right, but the decimal point is one place off. Estimate first: is the answer about as big as you expect?',

  /* ---- G5: order of operations ---- */
  'oo.lv1': 'Two operations, no brackets.',
  'oo.lv2': 'Division and subtraction.',
  'oo.lv3': 'Brackets.',
  'oo.lv4': 'Three operations.',
  'oo.lv5': 'Several brackets and operations.',
  'oo.p': 'Evaluate. \\({tex}\\)',
  'oo.h1': 'Order: brackets first, then multiply and divide from left to right, then add and subtract from left to right.',
  'oo.h2': 'Start with {first}',
  'oo.first.brackets': 'whatever is inside the brackets.',
  'oo.first.muldiv': 'the multiplication or division.',
  'oo.first.addsub': 'the addition or subtraction.',
  'oo.s.unbracket': 'The brackets only hold one number now: \\({expr}\\).',
  'oo.s.brackets-muldiv': 'Brackets first. Inside them, multiply or divide first: \\({expr}\\).',
  'oo.s.brackets-addsub': 'Brackets first. Work inside them: \\({expr}\\).',
  'oo.s.muldiv': 'Multiply or divide before adding or subtracting: \\({expr}\\).',
  'oo.s.addsub': 'Now add or subtract: \\({expr}\\).',
  'g5-order-of-operations.mc.went-left-to-right': 'It looks like you worked straight from left to right. Multiplication and division come before addition and subtraction.',
  'g5-order-of-operations.mc.ignored-the-brackets': 'It looks like the brackets were skipped. Whatever is inside brackets is done first.',

  /* ---- G7: integers ---- */
  'int.lv1': 'Add a positive and a negative number.',
  'int.lv2': 'Subtract to land below zero.',
  'int.lv3': 'Negative numbers added and subtracted, including subtracting a negative.',
  'int.lv4': 'Any signs, bigger numbers.',
  'int.lv5': 'Three terms.',
  'int.p.eval': 'Work it out. \\({tex}\\)',
  'int.p.rise': 'The temperature is {a} degrees. It rises {b} degrees. What is the new temperature?',
  'int.p.fall': 'The temperature is {a} degrees. It falls {b} degrees. What is the new temperature?',
  'int.right': 'right',
  'int.left': 'left',
  'int.h1': 'Picture a number line. Adding a positive moves right. Adding a negative moves left. Subtracting does the opposite.',
  'int.h2': 'Start at {acc}. Move {dir} {n}.',
  'int.s.flip': 'Subtracting \\({t}\\) is the same as adding {n}, so the move reverses.',
  'int.s.move': 'Start at \\({acc}\\). Move {dir} {n}. You land on \\({res}\\).',
  'g7-integers.mc.sign-of-the-answer-flipped': 'You have the right size but the wrong sign. Check which way you moved on the number line, and whether you ended up above or below zero.',
  'g7-integers.mc.ignored-the-negative-signs': 'It looks like the negative signs were ignored. A negative number sits left of zero, and that changes which way you move.',
  'g7-integers.mc.subtracting-a-negative-as-a-plain-subtract': 'It looks like subtracting a negative was treated like subtracting a positive. Taking away a negative is the same as adding the positive.',

  /* ---- G6: percent ---- */
  'pct.lv1': 'Percent of a number: 10%, 25% and 50%.',
  'pct.lv2': 'Percent of a number: multiples of 10%.',
  'pct.lv3': 'Percent of a number: 5%, 15%, 35%, 45% and 75%.',
  'pct.lv4': 'Find what percent one number is of another.',
  'pct.lv5': 'Find the whole when you know the part and the percent.',
  'pct.p.of': 'What is {p}% of {n}?',
  'pct.p.class': 'A class has {n} students. {p}% of them walk to school. How many students walk?',
  'pct.p.shirt': 'A shirt costs {n} dollars. It is on sale for {p}% off. How many dollars does the sale take off?',
  'pct.p.what': 'What percent of {n} is {part}?',
  'pct.p.walk': 'A class has {n} students. {part} of them walk to school. What percent of the class walks?',
  'pct.p.whole': '{part} is {p}% of what number?',
  'pct.p.sale': 'A jacket is on sale for {p}% off, which takes off {part} dollars. What was the original price, in dollars?',
  'pct.h1.of': 'Percent means out of 100. Write the percent as a fraction over 100, then multiply.',
  'pct.h2.of': 'Multiply \\({n} \\times \\frac{{p}}{100}\\).',
  'pct.h1.pc': 'Write the part over the whole as a fraction, then make the bottom 100.',
  'pct.h2.pc': 'Start with \\(\\frac{{part}}{{n}}\\).',
  'pct.h1.wh': 'The percent tells how many hundredths the part is. Work backward from the part to the whole.',
  'pct.h2.wh': '{p}% means \\(\\frac{{p}}{100}\\) of the whole is {part}. What number times \\(\\frac{{p}}{100}\\) gives {part}?',
  'pct.s.of1': '{p}% means {p} out of 100, which is \\(\\frac{{p}}{100}\\).',
  'pct.s.of2': 'Multiply: \\({n} \\times \\frac{{p}}{100} = {frac} = {part}\\).',
  'pct.s.pc1': 'Write the part over the whole: \\(\\frac{{part}}{{n}}\\).',
  'pct.s.pc2': 'Rewrite it with 100 on the bottom: it equals \\(\\frac{{p}}{100}\\).',
  'pct.s.pc3': 'Out of 100 means percent, so it is {p}%.',
  'pct.s.wh1': '{p}% of the whole is {part}. So {part} is \\(\\frac{{p}}{100}\\) of the whole.',
  'pct.s.wh2': 'Divide by the fraction: \\({part} \\div \\frac{{p}}{100} = {part} \\times \\frac{100}{{p}} = {n}\\).',
  'g6-percent.mc.forgot-to-divide-by-100': 'It looks like the last step is missing. Percent means out of 100, so divide by 100 after you multiply.',
  'g6-percent.mc.divided-by-the-percent-number': 'It looks like you divided the number by the percent. Instead, write the percent as a fraction over 100 and multiply.',
  'g6-percent.mc.used-the-percent-as-the-answer': 'The percent is the rate, not the amount. Find that rate of the number.',
  'g6-percent.mc.inverted-the-fraction': 'It looks like the fraction is upside down. The percent is the part over the whole.',
  'g6-percent.mc.gave-the-decimal-not-the-percent': 'That fraction is right, but a percent is out of 100. Multiply by 100 to turn it into a percent.',
  'g6-percent.mc.gave-the-part-as-the-percent': 'That number is the part, not the percent. Compare the part with the whole.',
  'g6-percent.mc.found-the-percent-of-the-part': 'It looks like you found the percent of the part. The part is already the percent of the whole, so work backward.',
  'g6-percent.mc.divided-by-100-only': 'It looks like you only divided by 100. The part is only the percent of the whole, so divide it by that percent as a fraction.',
  'g6-percent.mc.used-the-percent-as-the-whole': 'The percent is not the whole. The whole is the number that the percent of is the part.',

  /* ---- G6: mean ---- */
  'mean.lv1': 'The mean of three small numbers.',
  'mean.lv2': 'The mean of four or five numbers.',
  'mean.lv3': 'The mean of five or six larger numbers.',
  'mean.lv4': 'Find a missing value from the mean.',
  'mean.lv5': 'The mean of six to eight values.',
  'mean.p.eq': 'Find the mean of this data set: {list}.',
  'mean.p.games': 'A player scored these points in {n} games: {list}. What is the mean number of points per game?',
  'mean.p.quiz': 'A student got these scores on {n} quizzes: {list}. What is the mean score?',
  'mean.p.missing': 'The mean of {n} test scores is {m}. All but one of the scores are {list}. What is the missing score?',
  'mean.h1': 'The mean shares the total equally. Add everything, then divide by how many values there are.',
  'mean.h2': 'Add all the values. Then divide the total by {n}.',
  'mean.h1.m': 'If you know the mean and how many values there are, you can find the total.',
  'mean.h2.m': 'Total = mean \\(\\times\\) count = \\({m} \\times {n}\\).',
  'mean.s.a1': 'Add all the values: \\({sum} = {total}\\).',
  'mean.s.a2': 'Divide by how many values there are: \\({total} \\div {n} = {m}\\).',
  'mean.s.m1': 'The total of all the scores is the mean times the count: \\({n} \\times {m} = {total}\\).',
  'mean.s.m2': 'The scores you know add to \\({sum} = {ks}\\).',
  'mean.s.m3': 'The missing score is what is left: \\({total} - {ks} = {x}\\).',
  'g6-mean.mc.forgot-to-divide': 'It looks like you stopped after adding. The mean shares the total equally, so divide by how many values there are.',
  'g6-mean.mc.divided-by-the-wrong-count': 'It looks like you divided by the wrong number. Count every value in the data set, then divide the total by that count.',
  'g6-mean.mc.gave-the-median': 'It looks like you gave the middle value. That is the median. The mean is the total shared equally.',
  'g6-mean.mc.found-the-mean-of-the-known-scores': 'It looks like you averaged only the scores you know. Use the mean of all the scores to find the total first.',
  'g6-mean.mc.forgot-to-subtract-the-known-scores': 'You found the total of all the scores. Now take away the scores you already know.'
};
